### ISSUE TITLE
Mean and selected sample number are incorrect on clear

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#102]
Discovered in https://github.com/phetsims/projectile-data-lab/issues/101, if you press clear, you get null mean and sample 0/1:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/67a75429-73df-4dfe-94dc-cd7ad109399e)

**Comment by matthew-blackman** [comment]
This issue has been addressed by #103. Closing.
