### ISSUE TITLE
Two means appear on the histogram before it settles into a cadence

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#108]
In https://github.com/phetsims/projectile-data-lab/issues/91#issuecomment-1912783800 @catherinecarter said:

> I did notice that when I pressed the launch button while in continuous mode for the first time, there seems to be two means appear on the histogram before it settles into a cadence. In the video below, focus your attention on the histogram to see what I mean:

https://github.com/phetsims/projectile-data-lab/assets/109630002/06d7132d-6aad-439c-a42a-447cbc9d5800

**Comment by samreid** [comment]
OK this seems fixed in the commit.  Let's review/discuss.

**Comment by matthew-blackman** [comment]
Everything looks great here. Nice work! Closing.
