### ISSUE TITLE
Histogram expandedProperty should be featured

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#115]
From https://github.com/phetsims/projectile-data-lab/issues/30#issuecomment-1919750059:

> Histogram expandedProperty should be featured

We do not currently have a facility for modifying the AccordionBox.options.expandedPropertyOptions. To keep it simple, I just changed the property itself:

<details>

```diff

Subject: [PATCH] Remove extraneous stopwatch properties, see https://github.com/phetsims/projectile-data-lab/issues/30
---
Index: js/AccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/AccordionBox.ts b/js/AccordionBox.ts
--- a/js/AccordionBox.ts	(revision 31d4aaac1f5bf38c8ae26c39939e2c06a9d1ffad)
+++ b/js/AccordionBox.ts	(date 1706728674029)
@@ -250,7 +250,8 @@
     this.expandedProperty = options.expandedProperty;
     if ( !this.expandedProperty ) {
       this.expandedProperty = new BooleanProperty( true, {
-        tandem: options.tandem.createTandem( 'expandedProperty' )
+        tandem: options.tandem.createTandem( 'expandedProperty' ),
+        phetioFeatured: true
       } );
       this.disposeEmitter.addListener( () => this.expandedProperty.dispose() );
     }

```

</details>

That features all expandedProperty instances. When regenerating all API files like `grunt generate-phet-io-api --stable` it features the 4 expandedProperty instances in Calculus Grapher. Is that OK?

**Comment by arouinfar** [comment]
> That features all expandedProperty instances. When regenerating all API files like `grunt generate-phet-io-api --stable` it features the 4 expandedProperty instances in Calculus Grapher. Is that OK?

That sounds reasonable to me @samreid. I reviewed Calculus Grapher and only found 2 instances of `expandedProperty` but both of those seem reasonable to feature.

**Comment by samreid** [comment]
A heads up to @pixelzoom that I will be working in this area.

**Comment by samreid** [comment]
OK I featured the default accordion box expandedProperty, it is corrected in Calculus Grapher and Projectile Data Lab. Closing.
