### ISSUE TITLE
Sound design for field selector

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#118]
From the 1/31/24 PDL Sound Design meeting, we decided try the following ideas for the sound of the field selector buttons:

- Two tones played in tandem, mapping to the min and max of the field data
- Two tones played in tandem, mapping to the min and max of the histogram bins
- Multiple tones in quick succession, corresponding to the histogram bins

**Comment by samreid** [comment]
Did we consider playing rapidly through the projectiles from left to right?
