### ISSUE TITLE
Mean icon is not centered

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#122]
<img width="241" alt="Panel" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/2a6e2034-946b-4a9d-b9e1-369d78e22ba0">

The mean icon appears to be right-aligned instead of centered.

**Comment by samreid** [comment]
I added an AlignGroup which seems to help:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/4cc16203-b817-40d6-9a08-0db5e289ad8d)

I cannot explain why the interval tool icon is not centered.

**Comment by samreid** [comment]
@jonathanolson showed there are 2 `createCheckboxRow`. I can factor those out.

**Comment by samreid** [comment]
Fixed and reviewed with @matthew-blackman, closing.
