### ISSUE TITLE
Add initial sounds and mapping to the Angle Stabilizer slider 

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/projectile-data-lab#125]
I have provided a [mockup video here.](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/_layouts/15/stream.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FProjectile%20Data%20Lab%20HTML5%2FSound%20%26%20Sonification%2FMockup%20Videos%2FpdlAngleStabilizerRefVid%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview)

Here are the sounds:

- pdlAngleStabilizerClick2.mp3
- pdlAngleStabilizerClick1.mp3

As we discussed in our last meeting here is how I set up the mapping:

- There are two separate clicks being played at the same time (also we were going to try it with a delayed mapping to hear how it sounds)
- When the slider is at narrow (currently all the way left) both clicks play at the same playback speed
- When the slider is at wide (currently all the way right) one click plays +5 semitones higher in pitch, and the other click plays -5 lower in pitch
- This hopefully gives it the feeling of narrowing or widening

**Comment by samreid** [comment]
@matthew-blackman and I used the sound provided by @Ashton-Morris but did not fully implement the prescribed mapping.  @matthew-blackman will bring it up in an upcoming meeting.

**Comment by matthew-blackman** [comment]
I updated this with the new sounds from @Ashton-Morris and applied filtering to the min/max as discussed in the 2/14 sound design meeting. @samreid feel free to close if all looks good.

**Comment by matthew-blackman** [comment]
Reviewed this with @samreid and all sounds good. Closing.
