### ISSUE TITLE
Add sounds for custom launcher mechanism radio buttons on the Sources and Measurement screens

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/projectile-data-lab#126]
These are the sound for when you click on the custom launcher icon/buttons on the second scene.

I have the sounds we discussed and also three Air variations for you to try. They are in the Sound Files folder.

- pdlCustomLauncherButtonSpring.mp3
- pdlCustomLauncherButtonGunPowder.mp3
- pdlCustomLauncherButtonAirv1.mp3
- pdlCustomLauncherButtonAirv2.mp3
- pdlCustomLauncherButtonAirv3.mp3

**Comment by samreid** [comment]
Thanks, I committed the sounds and they will be ready to demo today.

**Comment by Ashton-Morris** [comment]
I have added this sound **pdlCustomLauncherButtonSpringv2.mp3** to our Sound Files folder. 

Can one of you put this in as an option? Emily messaged me that she would like to hear it in sim.

**Comment by samreid** [comment]
I added the given sound file and made it the default for now.

**Comment by Ashton-Morris** [comment]
Here are the updated sounds that we discussed in yesterdays meeting.

- pdlCustomLauncherButtonAirv4.mp3
- pdlCustomLauncherButtonSpringv3Longer.mp3
- pdlCustomLauncherButtonSpringv3.mp3

**Comment by matthew-blackman** [comment]
This was updated and reviewed by @emily-phet @Ashton-Morris and myself in the 3/1 sound design meeting. I add the latest spring and pressure sounds we worked on. Closing.
