### ISSUE TITLE
Landed projectiles have inconsistent opacity

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#128]
Playing with the sim, I noticed the cannonballs are much more transparent (maybe grey?) than the piano: 

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/37bb9b8f-8a8f-4e06-b33c-2932f2016c68)

With all 3 types together: 
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/0ede7548-ae9e-4161-ba8a-a74c13275592)

Curious if we should consider making the opacity upon landing consistent?

**Comment by samreid** [comment]
Working copy patch:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/0fcd702f-4249-404b-b4cb-398c7ee674af)

**Comment by samreid** [comment]
@matthew-blackman will adjust the colors separately.

**Comment by matthew-blackman** [comment]
I rebalanced the levels on the piano image to make it more clear that it was deselected. I think this is a good balance of saturation/brightness. I don't want to make the projectiles too washed out, to avoid the field looking like a gray blob when there are different types of landed projectiles. @catherinecarter can you review?

**Comment by catherinecarter** [comment]
It's better, but I still think the cannonballs are more muted than the other projectiles: 
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/758863f5-35dc-473a-b4ae-dff310aeeb11)

The difference between a landed and focused projectile is much more stark for the cannonballs, or maybe it's that the you can tell the pumpkin and piano are still their color, but the light is not shining on them as much, where the cannonball looks like there's a fog over it instead of a light just not making it as bright. Maybe a combination of both. Not sure, but the cannonball looks different. 
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/df291e08-9e6c-400e-a583-6741a7593822) ![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/fa46a1b8-f47e-437a-a3fe-5985387c623d) ![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/dca5b737-13ae-4152-a789-8bd4b26d5286)

Would it be strange to have a non-black piano?

**Comment by matthew-blackman** [comment]
Sounds good @catherinecarter! I updated the cannonball images so that the selected one looks highlighted instead of darkened. It's definitely an improvement. Can you take a look?

**Comment by catherinecarter** [comment]
Looks much better, I agree! 

One thing to note is that the pumpkin is a little dark on field 6 compared to field 1:
<img width="316" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/c8223357-7a19-4336-af16-efab791976d3"> 
<img width="322" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/f47719e4-ea37-4c90-b58b-42919e8d1772">

Not sure it's worth being a concern, but wanted to bring it up in case others felt the same way. But the cannonballs look much better.

I still think considering a different color for the piano would be worth exploring, since the two black objects get lost in each other: 
<img width="287" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/ca5d7c22-03c3-4351-8a22-acb1542a3801">

**Comment by matthew-blackman** [comment]
Sounds good @catherinecarter! I hear what you're saying. I'd like to keep it for now and see where we land on the projectile types. Reworking the piano graphics beyond an overall color filter would be a fair amount of work, but I agree that there is still room for improvement. Let's close this issue and decide if we want to open a separate graphics issue for the projectile images.

**Comment by matthew-blackman** [comment]
Reopening to share updated cannonball artwork from design meeting with @ariel-phet. Updating the cannonballs to a more 'steel' looking design provided good contrast with the pianos, and looked good on all field backgrounds. @catherinecarter can you weigh in? Feel free to re-close if all looks good here.

**Comment by matthew-blackman** [comment]
@catherinecarter, @samreid and I made some additional improvements to the cannonball selected image. Things are looking much better, and all projectile types are distinguishable from one another in both landed and selected states. Nice work! This issue can be closed.
