### ISSUE TITLE
Measures screen panel has inconsistent spacing

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#129]
On the Measures screen, the addition of the Interval Tool checkbox has created inconsistent spacing between checkboxes (the Stopwatch checkbox is closer to the Measuring Tape checkbox): 

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/aafab34c-89dc-4c99-8bc2-7ee516354870)

**Comment by samreid** [comment]
The fix in https://github.com/phetsims/projectile-data-lab/issues/122 seemed to help. Can this be closed?

**Comment by samreid** [comment]
This was fixed thanks to @jonathanolson in #122, closing.
