### ISSUE TITLE
Samples slow down on n = 40, continuous + fast mode

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#132]
When on n = 40, continuous + fast mode, the sample cadence slows down after about 150, and gets slower as the number gets closer to 200. I don't think I would have noticed except the sound got farther apart.

This phenomenon is true for all 6 launchers, and as far as I can tell, only for n = 40. Here's a video (hopefully the sound works in github):

https://github.com/phetsims/projectile-data-lab/assets/109630002/71c96b95-dd9c-4a31-bc98-fc925a9c73c6

**Comment by samreid** [comment]
Thanks for the great report! I am seeing the same thing. The CPU gets progressively more used, check the top yellow curve in this profiling run:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/efb2e182-3dec-4f1b-b301-3d65833ed11d)

The time is around 84% in getHistogramData.  If it cannot easily be optimized, then I think it would be very amenable to caching. I'll take a look.

**Comment by samreid** [comment]
@matthew-blackman and I improved the performance by making sure to iterate through the projectiles just once. Closing.
