### ISSUE TITLE
Sampling eraser button should be more discoverable

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#136]
@catherinecarter pointed out that the location of the eraser button in the Sampling histogram makes it difficult to discover. We want to try two options to improve this.

1. Moving the eraser button below the histogram, in place of the 'Blocks/bars' toggle. This will cause the 'Blocks/bars' toggle to move to the left.
2. Moving the eraser button next to the Reset all button. Since this is next to the field sign with the information of all samples on the current field/histogram, this would be a reasonable location to clear the field. It would also make clear that there are two different ways to reset data on this screen.

Let's implement this once https://github.com/phetsims/projectile-data-lab/issues/104 is complete.

**Comment by matthew-blackman** [comment]
I mocked up the two options described above in Photoshop. I feel that both options are an improvement on the current design, and would have a slight preference to option 2. @catherinecarter what do you think?

<img width="1209" alt="Screen Shot 2024-02-07 at 1 12 43 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/378109ee-5e7e-4712-a10e-3568ce4bc6f4">

**Comment by catherinecarter** [comment]
Like other components, I think consistency is important. While the eraser has different functionality on the VSM screens than the Sampling screen, I think having it next to the 'erase all' button makes the most sense (option 2), at least for now. 

Not having it in the same location opens the opportunity for students to either 1) not see it at all (which is what was happening with the eraser in the histogram itself), or 2) think it does something different or is special. If students thought #2 was the reason, this would be ok since it's true, but more importantly, they'd have to find the button in the first place. 

Let's add it to the interview list and see if students figure out that the eraser does different things on the screens, and if it seems problematic, we can consider option 1. Sound good?

**Comment by samreid** [comment]
@matthew-blackman and @catherinecarter and I decided we will try it by the reset all button.

**Comment by samreid** [comment]
I implemented the recommendation. It seems to be working well. @matthew-blackman want to take a look? Feel free to close if all is well.

**Comment by matthew-blackman** [comment]
@samreid the UI is looking much better and consistent across all screens. Having the eraser and clear all buttons next to each other make it clear to the user that there are 2 different types of reset, which communicates the UX well. Nice work! Simpler ended up being better here.

My one remaining qualm is that the eraser and reset buttons look odd when next to each other since one is rectangular and the other is circular. I know it is this way in some other sims, but I think the layout of the buttons can be improved.

Here is the current layout, which I think makes the eraser button look small:
<img width="147" alt="Screen Shot 2024-02-12 at 1 17 36 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/c9ad77b4-9f84-4888-a7ec-71d2ec2ad866">

I recommend trying a more square shaped button for the eraser, and setting the two buttons to be the same size. The bounding box of the eraser button icon is square as well, so this also improves the consistency of the margins around the eraser icon.
<img width="147" alt="Screen Shot 2024-02-12 at 1 18 00 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/59b3b1f8-9f00-4c78-9e66-6a551618dd75">

I'd like to implement this in the sim, and see how we can make the eraser button look more consistent with the clear all button. @catherinecarter will tag you for review when ready.

**Comment by matthew-blackman** [comment]
@ariel-phet mentioned that the eraser button looks reasonable as a square button. He also mentioned that its area is slightly larger than the circular clear-all button, which is likely a benefit to the sim since this is the primary UI button we want users to click when clearing their data. I feel that this issue can be closed. Please reopen if you feel otherwise.
