### ISSUE TITLE
Sound on Sampling screen is odd

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#137]
On the Sampling screen for any launcher, any sample size, I was listening to the mean bounce around on Continuous and Fast mode. 

There seems to be a "woodpecker-like" knock hidden behind the mean sound. I can't hear it as much, or at least it's not distracting enough to notice, when on Continuous and Slow mode, or on Single Sample mode fast or slow.

@Ashton-Morris, is there a way to change the sound of the mean to eliminate (or diminish) the woodpecker effect when the mean is played quickly? I don't know the correct lingo here, but the sound itself is great, except for that knock at the front of the sound (I think?).

**Comment by Ashton-Morris** [comment]
I have added this sound **numberToneLessAttack.mp3** to our sound files folder.

Can we try this one and see if it helps with that woodpecker effect?

**Comment by matthew-blackman** [comment]
This sounds great! I implemented the new sound and the clicking effect is gone. Nice work! Closing, but feel free to reopen if you feel otherwise.
