### ISSUE TITLE
Consider changing the location of the radio buttons on Measures Screen?

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#138]
I am finding the radio buttons to be in an awkward position on the Measures screen to choose between the Mystery and the Custom launchers: 
<img width="205" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/44ea1b42-8129-4efb-87f4-961c4f044b41">

Curious if it would make sense to move them under the launcher selection group so all the buttons are together? 

I don't know of a good solution or suggestion, but for me, having 2 groups of icons, and then traditional radio buttons, and then more icons is visually hard to extract the vertical (non-icon) radio buttons.

**Comment by matthew-blackman** [comment]
@catherinecarter, @samreid and I think that this can be solved by centering the Mystery/Custom radio button group. We implemented this in the above commit, and it really improves the design and discoverability of the radio buttons. Nice work! Closing, feel free to reopen if there are further changes recommended.

**Comment by catherinecarter** [comment]
Reopening because I think there's a little too much padding around the top/bottom of the radio button group:
<img width="202" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/06e68a48-b177-4eba-aaf0-a1545540f356">

It's making the "No Air Resistance" phrase occlude the speed tool.

**Comment by matthew-blackman** [comment]
Discussing this with @catherinecarter, we'd like to reduce the y-margin on the radio button group a little bit, and add some y-margin to the headings in the launch panel. We will also need to check for overlap with the speed tool in the lowered state. Let's try it!

**Comment by matthew-blackman** [comment]
We reduced the y-margin of the Mystery/Custom radio button group, which improved the launch panel layout significantly. With the updated layout, the panel sections are looking consistent and I don't think we need to add space to the section headings. Closing, but please reopen if you feel otherwise.
