### ISSUE TITLE
Pumpkin and Piano sounds

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#140]
From https://github.com/phetsims/projectile-data-lab/issues/106, we are considering that the pumpkin and piano may want to sound different on landing.  Some proposed sound effects were listed in https://github.com/phetsims/projectile-data-lab/issues/106#issue-2103017877

**Comment by samreid** [comment]
In the meeting, we discussed that a more subtle difference may work well. @matthew-blackman recalls @Ashton-Morris was asked to work on that.

**Comment by samreid** [comment]
I added a projectileType parameter to LandingSound so it will be easy to try different sounds. Self-unassigning.

**Comment by samreid** [comment]
In https://github.com/phetsims/projectile-data-lab/issues/133#issue-2121829583 @matthew-blackman said:

> In the 2/6 PDL Sound Design meeting, it was discussed that we want to try a subtle differentiation of projectile landing sound for cannonballs, pumpkins and pianos. @Ashton-Morris is going to mock up some options.

**Comment by Ashton-Morris** [comment]
I am adding these sounds to our Sound Files folder. The intended implementation is to have their playback speed randomized by 4 semitones each time the sound is triggered. And to play along with the Landing Tone.

- pdlCannonBallLandMuffled.mp3
- pdlPumpkinLand-001.mp3
- pdlPianoLandv1.mp3
- pdlPianoLandv2.mp3

**Comment by samreid** [comment]
Thanks! Can you please clarify this part?

> randomized by 4 semitones

Does it mean: a uniform distribution of random floating point numbers within +/- 4 semitones?  Or does it mean discrete choices like -4,-3,-2,-1,0,1,2,3,4? Or something else?

**Comment by Ashton-Morris** [comment]
In my its (play with in the range -2 to +2 semitones) at random for each playback. So I think it would be random floating point numbers.

**Comment by samreid** [comment]
OK I updated the range of semitones accordingly.

**Comment by Ashton-Morris** [comment]
@matthew-blackman I had in my notes that we wanted to try a few pumpkin landing variations and compare them to what we have. I have added these to our sound files folder.

- pdlPumpkinLandv2.mp3
- pdlPumpkinLandv3.mp3
- pdlPumpkinLandv4.mp3

**Comment by matthew-blackman** [comment]
This was reviewed and approved by the sound design team on 3/1. Nice work all! The projectile landing sounds are excellent and the sim is sounding great. Closing.
