### ISSUE TITLE
Projectile type can address additional learning goals

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#142]
Currently the projectile type is purely an aesthetic difference to address the learning goal of measurement uncertainty. During interviews, both students changed the projectile type and noticed that it had no effect on the launch, and moved on. I think this may be a missed opportunity, and that the projectile type opens up avenues to address learning goals that we have not yet explored.

Currently the launch speed for all projectiles is centered around the same average (25 m/s). Although each launch mechanism (spring, pressure, explosion) has a different SD of speed, it is nice that they all have the same average speed so that they are a single-dimensional control. However, the projectile type could be a natural way to open up exploration about the average speed. This would give independent ways for students to adjust the SD of speed without affecting the average, and also adjust average speed without changing the SD (by much).

After discussing this with @catherinecarter and @samreid, we found that there are many strong benefits that this would offer to the sim, as well as some drawbacks. The idea is that each projectile type would have a 'speed multiplier' that would be used to find the mean speed for its launch. This would be PhET-IO instrumented, similar to LauncherMechnaismIO. We would not need to state the mass of each projectile type, since this could be kept intentionally vague as a categorical variable, and not given too much emphasis. Here is some of what we discussed so far:

Benefits:
- Having projectile type affect the launch creates more avenues for student exploration and curiosity.
- Having a way to change the launch speed mean and SD independently allows for more dimensions of student investigation.
- Changing the mean speed allows for more options for distributions, including bimodal and trimodal distributions, for students to explore.
- This would not affect the learning goal about measurement uncertainty, since students could pumpkins for a lesson about measurement.
- This creates interesting possibilities for sonification, with different combinations of same/different mean/SD all having unique soundscapes.
- This would naturally address the science learning goal of correlation between the mean and SD, which is otherwise challenging to see in the sim with the current free parameters.

Drawbacks:
- If we decide to display different values for projectile mass, we will need to explain in the documentation how the arbitrary mapping works.
- This disallows students from using the projectile to differentiate data sets for different angles or launchers, since projectile type would now be a confounding variable. However this was never the intended use of the projectile type, and is more the role of the field selector.

I would like to spend some time implementing a mockup of this to see how it behaves in the sim, to help frame further discussion.

**Comment by matthew-blackman** [comment]
This was quick to implement so I gave it a go. Here are some screenshots of things that are now possible that weren't before:

<img width="1396" alt="ProjectileTypeScreenshot1" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/033d41b2-29d9-4110-8c79-dd69f35b7fbf">

<img width="1396" alt="ProjectileTypeScreenshot2" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/7d86a8e4-8ec6-434f-b321-61d638c6c149">

Seeing/hearing this in action, I feel that it offers significant benefit to the sim, with new avenues for exploration and additional ways to arrive at the learning goals. I'd like to hear how others feel.

@catherinecarter and @arouinfar, can you experiment with this and weigh in?

**Comment by catherinecarter** [comment]
I love it! 

I can now create a distribution on the Measures screen with the same projectile (say cannonball), then, once I've figured out that the pumpkin will fly farther, ask students to predict what will happen to the mean when a projectile lands to the right of the rest of the distribution. They might finally get it when an instructor says, "the mean is pulled in the direction of an outlier."

**Comment by emily-phet** [comment]
You could potentially allow enabling/disabling this feature in the Preferences menu. I think a reduced set of options would make this sim more accessible to younger audiences, so something to consider from that perspective.

**Comment by matthew-blackman** [comment]
@emily-phet I agree that reducing the options would improve accessibility for younger students, but I also feel that this feature could be a good one for them to start with. Seeing the pumpkin/piano go different distances feels more straightforward and tangible to me than switching a launcher and having the variability change. I think the biggest contributor to the issue you pointed out is the mystery launcher UI. What do you think? I'm also happy to open a side issue to discuss ways to improve the accessibility to younger audiences.

**Comment by samreid** [comment]
We would like to add a sim-specific preference + query parameter: "Projectile type affects launch speed" which is true by default.

**Comment by matthew-blackman** [comment]
@samreid and I added a preferences option for 'projectileTypeAffectsLaunchSpeed', which is 'true' by default. This is a nice option for users to have. We tested the behavior and all looks good. This issue can be closed.
