### ISSUE TITLE
Interval tool icon is not center aligned with other icons

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#144]
The interval tool icon should be horizontally centered with the other icons in the panel.

![ IntervalToolIcon](https://github.com/phetsims/projectile-data-lab/assets/108756567/ec046817-c1ef-4cc6-88f2-2869e180a512)

**Comment by samreid** [comment]
I think the problem was actually the stopwatch icon was offcentered, I corrected it in the commit.

**Comment by matthew-blackman** [comment]
Looking great! Reviewed - nice change. Closing.
