### ISSUE TITLE
Vertical axis label of histogram is not centered

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#145]
It looked strange to me that the y-axis label was not centered on the y-axis. Centering it caused it to run up against the zoom buttons, so I center-aligned those with the zero of the y-axis. This also looked better when the bin control UI was left-aligned with the left edge of the histogram chart. Here is a screenshot of the latest:

![HistogramLayout](https://github.com/phetsims/projectile-data-lab/assets/108756567/92bf772a-2f98-4573-b892-0152ac982a9f)

Let's discuss if we would rather have the 'Count' label be centered on the y-axis, or if we want the zoom buttons to be bottom-aligned with the bottom of the histogram. It doesn't look like we have enough space to do both, so we should decide which is preferable. @catherinecarter and @arouinfar can you weigh in?

**Comment by arouinfar** [comment]
@matthew-blackman I like the alignment in your screenshot. Centering the zoom buttons on the zero makes sense and gives us enough room to center the y-axis label.

**Comment by matthew-blackman** [comment]
Sounds good @arouinfar! Things are looking good here. I think this issue can be closed.
