### ISSUE TITLE
Projectile landing should play a 'landing sound' and a 'distance tone'

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#147]
In the 2/9 sound design meeting, we discussed that two sounds should be played when a projectile lands or becomes selected.

- A 'landing sound', which is different for each projectile type. We may want to consider a random pitch shift if this is sounding repetitive, especially in Fast mode.
- A 'distance tone' which is the same for all projectile types, but varies with distance.

We also want to consider whether selecting a projectile through the projectile selector panel would play both sounds, or just the distance tone.

Additionally we would like to try using the 'landing sound' for the projectile type buttons.

**Comment by samreid** [comment]
Keep in mind new sound effects are being designed for https://github.com/phetsims/projectile-data-lab/issues/140#issuecomment-1933266859

**Comment by matthew-blackman** [comment]
During the 2/13 sound design meeting, it was decided that we should keep both the projectile landing sound and distance tone in the data selector sound. Having this information sonified in data navigation was beneficial to differentiating data sets and hearing the effect of projectile type. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
I moved the issue to https://github.com/phetsims/projectile-data-lab/issues/161, closing
