### ISSUE TITLE
Add ticking sound to stopwatch

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#149]
In the 2/9 Sound Design meeting, @Ashton-Morris demoed two sound effects for the ticking of the stopwatch. This seems like a useful feature for this sim. Since the stopwatch is a common component, any sounds we implement here should probably be in common code. But in the meantime, we can implement this on a sim-specific level to hear how it sounds.

**Comment by samreid** [comment]
I do not see any ticking sounds listed in the [sharepoint folder](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?csf=1&web=1&e=k9slyK&cid=319abee1%2D2f2a%2D41d2%2D868d%2D8298d77e8721&RootFolder=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FProjectile%20Data%20Lab%20HTML5%2FSound%20%26%20Sonification%2FSound%20Files&FolderCTID=0x0120001AF96E22694A1A448A9649A49C4AC974), so I'll reassign to @Ashton-Morris to check on the status.

**Comment by Ashton-Morris** [comment]
I have added these files to our Sound Files folder.

- pdlStopwatchTickA.mp3 
- pdlStopwatchTickB.mp3

**Comment by matthew-blackman** [comment]
From @emily-phet's feedback in the Sound Design doc:

I think this needs to sound pretty subtle and tonal. Examples in Friday’s discussion felt too “clicky” and too sharp. When someone is using the stopwatch they need to be attending to something else as well, not just watching the watch so it needs to feel more background and less in-your-face.
- Recommendation: Let’s try a few demos that sound, like the following:A simple wood block sound
o Something that’s more like cross between a wood block sound and a click. I think there might need to be some slight click character to make it clearly associated with the passage of time…and just a wood block sound might feel discrepant and out of nowhere. 
o Like a soft version of this: https://www.youtube.com/watch?v=G4au0JR0xwg


 pdlStopwatchTickA sounds good to me. I'd be open to hearing a more wood block-y sound as well. Let's try some alternatives @Ashton-Morris.

**Comment by Ashton-Morris** [comment]
I agree, I also like pdlStopwatchTickA.mp3  and pdlStopwatchTickB.mp3 but I will try to mock up some wood block-y sounds.

**Comment by Ashton-Morris** [comment]
@matthew-blackman I added these sounds into our folder to replace the existing sound as discussed in todays meeting.

- pdlStopwatchTickWoodA.mp3
- pdlStopwatchTickWoodB.mp3

**Comment by matthew-blackman** [comment]
pdlStopwatchTickWoodB.mp3 sounds great here. The sound is implemented in PDL, but we haven't discussed if/how this could affect stopwatches in other sims. @samreid let's discuss when we come back to this issue.

**Comment by samreid** [comment]
@matthew-blackman and I discussed this, and agree the sound is working well for Projectile Data Lab. When other sims with stopwatches become sonified, that will be an appropriate time to evaluate how it should sound in that context. Closing.
