### ISSUE TITLE
Add custom sounds to Histogram Toggle

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#150]
In the 2/9 Sound Design meeting, @Ashton-Morris demoed sounds for the toggle switch. They sounded great and we'd like to implement them for the Histogram toggle (blocks/bars).

**Comment by samreid** [comment]
I do not yet see the sound effect in the sound folder. Assigning to @Ashton-Morris to provide the audio.

**Comment by Ashton-Morris** [comment]
I have added these files to our Sound Files folder.

1. pdlToggleButtonA.mp3
2. pdlToggleButtonB.mp3

**Comment by matthew-blackman** [comment]
This sounds great! @samreid and I reversed the sounds so that a rising tone is played when switching from left -> right, and a falling tone from right -> left. This seemed correct to us and sounded good in the sim. Closing.
