### ISSUE TITLE
`stopwatchNode.visibleProperty` should be derived from state of checkbox

### ISSUE THREAD

**Issue by arouinfar** [phetsims/projectile-data-lab#151]
@matthew-blackman @samreid while reviewing the tree for #29, I noticed that the StopwatchNode has a `visibleProperty` that behaves independently of the Stopwatch checkbox (`model.stopwatch.isVisibleProperty`). 

Notice the stopwatch is visible, but the checkbox is not checked:
![image](https://github.com/phetsims/projectile-data-lab/assets/8419308/05cfebd0-4f19-49a5-91de-aceb55ed3aca)

The tree currently looks like this:
![image](https://github.com/phetsims/projectile-data-lab/assets/8419308/d952b3c5-ce22-49d8-8eea-003bf6ea4ce5)

Instead of `view.stopwatchNode.visibleProperty` I would expect to see `*visibleProperty` link to `model.stopwatch.isVisibleProperty`, similar to how we do things for the MeasuringTapeNode:
![image](https://github.com/phetsims/projectile-data-lab/assets/8419308/0fe33ddb-f9d9-402e-b617-1f54c4011775)

**Comment by samreid** [comment]
Good idea, thanks! Fixed, pushed and closing.
