### ISSUE TITLE
Normalize all audio filenames

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#152]
Discovered in https://github.com/phetsims/projectile-data-lab/issues/126, it is confusing to rename files to match the simulation then have to discuss them with different names in the issues. So for now I'll commit the filenames that are given (that match the filenames in sharepoint), but before publication, we should standardize the filenames. Remove pdl prefix. Get rid of version identifiers, fix casing.

**Comment by matthew-blackman** [comment]
All files are updated. Closing.
