### ISSUE TITLE
Add Field.color

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#154]

**Comment by samreid** [comment]
This commit helped a lot and cleaned up the type issues we saw last week. @matthew-blackman can you please review, in particular:

* Are the colors correct?
* Do you want to move the PDLUtils functions to their usage sites?

**Comment by matthew-blackman** [comment]
This cleaned things up nicely. Great work! The colors are correct and the changes have been reviewed. Everything looks great. I don't see a reason to move the PDLUtils functions to their usage sites, so I feel this issue can be closed. If anyone disagrees feel free to reopen.
