### ISSUE TITLE
Standard deviation value in the sim may not be correct

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#155]
I was playing with the sim embedded in CODAP and noticed that the value of the standard deviation sometimes differs from the SD calculated in CODAP. Here's an example where the sim gives 8.09 as the SD but CODAP calculated 8.24: 

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/88b0e5bd-1b49-45ee-86de-a03f341ce47c)

Let's make sure the SD in the sim is calculating this value correctly.

**Comment by samreid** [comment]
I'm not sure how to read the standard deviation in CODAP, so I exported the CODAP data to excel, and also saw a difference:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/9f0ba9a1-c53a-43f1-bf7e-ef7219b08a7f)

**Comment by samreid** [comment]
Excel is showing STDEV.S and we are computing STDEV.P. When I compute STDEV.P in Excel, it matches our value.

**Comment by samreid** [comment]
Is codap showing the sample standard deviation or population standard deviation?

**Comment by catherinecarter** [comment]
CODAP is using stdev.s, which means it's calculating the SD from a sample. The stdev.p is for the population. The difference is the denominator. The formulas are:
- stdev.p = $\sqrt{(x_i – mean)^2/n}$       
- stdev.s = $\sqrt{(x_i – mean)^2/(n – 1)}$

Since the projectiles on the field are considered (I think?) to be a sample from the infinite population of the cannon, we need to use stdev.s, or the sample standard deviation (the .s = sample; .p = population). 

For reference, the population standard deviation is the set value embedded into each cannon, although these are set as speed and angle SDs, but each impacts the true population standard deviation of the landing positions. 

Does that help build clarity?

**Comment by matthew-blackman** [comment]
The fix was erroneously committed to https://github.com/phetsims/projectile-data-lab/issues/156. My fault! The good news is that everything is behaving perfectly here now. Nice work! Closing.
