### ISSUE TITLE
Selected sample size thumbnail should be highlighted

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#157]
Discussing the Sampling screen with @ariel-phet, we decided to make it more clear which sampling thumbnails is currently being shown in the histogram. Let's try to do this using a stroke, without making it look clickable.

<img width="1085" alt="Screen Shot 2024-02-13 at 11 15 42 AM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/cb4839ee-b57c-4b33-8366-a2b406439180">

**Comment by samreid** [comment]
Implemented in the commit, it currently looks like this:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/2055cc8a-bfde-44bb-8418-dfb5663a9d9d)

Assigning to @matthew-blackman to review the behavior, implementation and fine tune the line width as necessary.
