### ISSUE TITLE
Sampling histogram info panel changes size

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#158]
This happens when the number of samples increases in length. Let's make it a constant size, and leave padding when the numbers are single or double-digit.

**Comment by samreid** [comment]
I started with this patch:

<details>

```diff

Subject: [PATCH] Highlight the selected thumbnail node, see https://github.com/phetsims/projectile-data-lab/issues/157
---
Index: js/sampling/view/SamplingHistogramNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/sampling/view/SamplingHistogramNode.ts b/js/sampling/view/SamplingHistogramNode.ts
--- a/js/sampling/view/SamplingHistogramNode.ts	(revision a8e4a36fafbbd69fd611e569a39ee5027104bb6c)
+++ b/js/sampling/view/SamplingHistogramNode.ts	(date 1707864995157)
@@ -84,7 +84,9 @@
       children: [ iconNode, textVBox ]
     } ), {
       fill: 'white',
-      cornerRadius: 5
+      cornerRadius: 5,
+      minWidth: 200,
+      maxWidth: 200
     } );
     this.chartNode.addChild( textPanel );
 

```

</details>

The problem is that when the translation changes, the panel doesn't know to shrink:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/0f584077-68db-43c1-bf1e-03d8c6833185)

I'm not sure how to have the panel "fit" the text when translation changes but not when the number changes.

**Comment by samreid** [comment]
OK I addressed it in the commit. I tried to thoroughly address the various cases of string lengths, so the solution is a bit more complex. But it seems nice at runtime and in the string length tests.  @matthew-blackman can you please review and close if it seems ok?

**Comment by matthew-blackman** [comment]
Reviewed - I really like how you implemented this @samreid. Everything looks good in the panel, and I learned how to use the bounds of a node that isn't added to the scene. Nice work! Closing.
