### ISSUE TITLE
Sound balancing

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#161]
Overall sound balancing

**Comment by samreid** [comment]
Pickup/drop sounds were recently added for the draggable tools (stopwatch, measuring tape), and they likely need balancing.

**Comment by matthew-blackman** [comment]
From 4/5 meeting with AshM:

- Reduce histogram bin tone by 10%
- Increase mean tone for measures histogram by 20%
- Reduce stopwatch sound volume by 40%
- Reduce toggle switch volume by 30% (same volume as accordion box expand/collapse)
- Reduce interval tool edges to sound the same volume as the middle (about 15% quieter)
- Interval tool min and max should be 10% lower

**Comment by matthew-blackman** [comment]
All of the above items are complete. The sim sounds great. Nice work! Closing.
