### ISSUE TITLE
Gray out the stopwatch launch button when no more projectiles can be launched

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#164]
Discovered in https://github.com/phetsims/projectile-data-lab/issues/146, if you exhaust all projectiles, the stopwatch launch button should probably gray out.  @matthew-blackman sound good?

**Comment by samreid** [comment]
Fixed. @matthew-blackman want to review/test? Please note it seems important to leave the "stop" functionality enabled even when all projectiles are exhausted.

**Comment by matthew-blackman** [comment]
Code changes look great, and everything worked correctly in my testing. Nice work! Closing.
