### ISSUE TITLE
Ghost data point?

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#170]
I'm not sure if this is a bug or not, but when I used the autoGenerateData=true with launcher 6, I see this: 
<img width="1195" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/59631313-0c5b-4c17-b3fd-8b334f16077b">

As you can see, there's a dot on the histogram between 0 and 5 meters being highlighted on the histogram, but there's no pumpkin on the field. Or maybe the cannon is occluding it?

Here's a picture with bin width = 0.5, so it's possible there's a pumpkin on the zero line, but it would seem like we could see a sliver of it, even if it's really far left: 
<img width="1185" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/20c920bd-c321-4995-a24c-9f6b80701287">

Anyway, wanted to bring it up that if a pumpkin lands in the cannon circle, it's not visible. Maybe we'd want to show an outline of one similar to when a projectile is halfway off the 100m line?

**Comment by matthew-blackman** [comment]
In the 2/29 design meeting, the design team agreed that we can disallow negative angles when launching from ground level. Additionally, we'd like to guarantee that launch speeds cannot be negative. Since these only affect 1 in over 10,000 projectiles, this will have a negligible affect on all statistical measures. 

We should add a line of documentation in the implementation notes to make it clear that we are doing this, and explain that it is consistent with the physical limitations of a projectile launching apparatus.

**Comment by matthew-blackman** [comment]
The above commit removes negative angles except when the launcher is raised. This brings the chances of a projectile launching behind the launcher from 1 in 5,000 to 1 in over 50,000. There is always a chance that a projectile will become a "ghost" data point, but the team felt that if this was exceedingly rare, it would at worst present an interesting question for the student.

I also removed negative speeds in the commit, although the odds of a negative speed are basically zero including with  PhET-IO. The minimum possible mean speed is 15, and the maximum speed standard deviation is 1.5.

@samreid can you review the implementation? I was a bit verbose to favor readability. Hoping to discuss.

**Comment by catherinecarter** [comment]
I played with the new setting for a bit on auto-generate and got one instance in about 20-25 launches where a pumpkin landed very close to the launcher (launched with: launcher 6, pumpkin, 60º setting). I could see a piece of it on all but the 30º setting, but I agree, it would make for an interesting conversation. In the teacher tips, we could add a tip to change the angle to see the projectile if this situation presents itself. Screenshots below in order of 30º, 45º, 60º, 0º:

<img width="173" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/d4277072-c33c-412e-985d-89c62664196e">   <img width="169" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/b9956bf0-3dfc-4e30-b906-7c989f60a21b">   <img width="177" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/8fdf8645-3797-49ab-9c6d-78741268ebce">  <img width="171" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/e5f89a0c-35c2-48da-8e01-88e4be25d806">

**Comment by matthew-blackman** [comment]
This has been reviewed with @catherinecarter and @samreid, and updated in the commit. Nice work all! Closing.
