### ISSUE TITLE
Add sound to the interval tool

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#173]
In the 2/23 sound design meeting, @emily-phet @Ashton-Morris and I discussed sonifying the interval tool. We'd like to try a 'ratcheting' sound behavior, playing a sound every time a threshold is passed. We recognize that this is different than the interval tool in CAV, and would like to explore a different mode of sonifying the center and spread.

The behavior we'd like to try is as follows:
- When picking up or putting down the interval tool body or handles, they should play a 'grab'/'ungrab' sound
- When dragging the handles, a sound should play when the width of the tool passes a certain threshold. The pitch of this sound should change with the width of the tool - a wider interval making a deeper tone. We'd like to try a 2-meter threshold for a first pass.
- When dragging the body of the interval tool, a different sound should play when the center of the tool passes a threshold. Let's use the same 2-meter threshold as a first pass.
  - We should add a 'center line' visual when translating the tool to make this more clear.

**Comment by matthew-blackman** [comment]
This has been implemented and this issue is ready for review! @catherinecarter we used a 5-meter threshold for triggering the sounds. Can you take a look/listen and provide feedback?

**Comment by catherinecarter** [comment]
Overall, I like the sound. When I moved the tool slowly, the 5 m threshold felt like a long time. But when I moved it quickly, it felt right. Not sure where the balance is there, or if it needs to be changed at all, but wanted to mention it.

Also, when I was moving the tool with tab/arrows, the sound was very distracting unless I pressed and held the arrow. I don't know how students needing alt-input typically interact (pressing arrow keys repeatedly versus pressing once and holding), and I'm also not sure how anyone needing or using alt-input would expect the interaction/sound to occur, but it was very distracting to hear so many sounds simultaneously (unless holding the arrow down). I don't have a solution, but like above, wanted to mention it. 

I like the sound, though, in general, and I like that the center is highlighted when translating the interval across the field. I'll play with it some more tomorrow and see if I agree with myself from today :)

**Comment by Ashton-Morris** [comment]
I agree with part of what @catherinecarter mentioned. I think the grab-letgo sound would ideally play once when you Tab to highlight the tool for intended use with the keyboard. I feel like highlighting it to me means "grabbing it" and its not really "letgo" until you tab to another area with the sim.  So playing the grab-letgo sound whenever you press the arrow key feels unnatural. 

I have a particular aversion to this sound and we tried a similar sound with JB in another sim and I felt the same way. To me it feels too much like knuckles cracking or insects or something I get a "spine tingling feeling" when I hear it. I'd prefer we try a different kind of clicking sound.

**Comment by matthew-blackman** [comment]
From the 2/27 sound meeting, the interval tool sound behavior is mostly good. @emily-phet @Ashton-Morris and I felt that the drag handles did not need a grab/release sound, since they are essentially 1-dimensional sliders. We'd also like to try softer and less click-y sounds for the ratcheting effect, to give the tool a softer feel. Let's remove the grab/release sound and experiment with different sounds.

**Comment by matthew-blackman** [comment]
I tried out different sound files and mappings and went with a sound and filter that had less clicking than before. @Ashton-Morris can you review and provide feedback?

**Comment by Ashton-Morris** [comment]
I think it sounds great. Very simple, clean and easy on the ears. I particularly enjoy the end boundary sounds when you are moving the whole thing.

**Comment by matthew-blackman** [comment]
This was reviewed by @emily-phet @Ashton-Morris and myself in the 3/1 sound design meeting. Everything sounds great! Closing.
