### ISSUE TITLE
Don't enable histogram sound button in Sampling-Continuous

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#181]
@Nancy-Salpepi noticed that the histogram sound button becomes enabled on the Sampling screen when switching to Continuous mode, even if there is no data. This is a bug. Let's fix it!

**Comment by samreid** [comment]
I committed a proposed fix. @matthew-blackman can you please review and test?

**Comment by matthew-blackman** [comment]
Your solution worked for me @samreid but required adding a property to the multilink. I committed a proposed solution that I believe will also work but not require an additional dependency. Can you spot check?

**Comment by samreid** [comment]
The proposal looks preferable and is testing well on my side, thanks. Closing.
