### ISSUE TITLE
implementation-notes.md, Does it provide an overview that will be useful to future maintainers?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#185]
https://github.com/phetsims/projectile-data-lab/blob/main/doc/implementation-notes.md

**Comment by pixelzoom** [comment]
I reviewed implementation-notes.md for code review #32.  It seems reasonable to me, and I made a couple of minor changes in the commits linked directely above this comment.

**Comment by samreid** [comment]
Excellent, thanks!  I'll close this one and leave https://github.com/phetsims/projectile-data-lab/issues/184 for @matthew-blackman to sign off. Closing.
