### ISSUE TITLE
Sim-specific query parameters need documentation.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#195]
For code review #32 ...

There is currently no documentation for public query parameters, sparse documentation for private query parameters.

Somethings that are useful to include in doc:
* For public query parameters, think in terms of the doc that you would share with end users, via examples.md and/or Teacher Tips.
* Whether a query parameter is used to initialize a Property
* Whether a query parameter is related to a preference
* Links to GitHub issues where decision were made about adding query parameters

**Comment by samreid** [comment]
I updated the documentation in the commits. Closing.
