### ISSUE TITLE
Naming convention not followed in PDLColors.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#196]
For code review #32 ...

For color profiles, there is a naming convention that is not being followed.  If `blahProperty` is the field name, then the argument to `colorName` argument to ProfileColorProperty should be `'blah'`.

In PDLColors.ts there are many names that do not follow this convention.  For example:

```ts
  panelColorProperty: new ProfileColorProperty( projectileDataLab, 'panelFill', {
    default: 'rgb(243,243,243)'
  } ),
```

There is no correspondence between `panelColorProperty` and 'panelFill'.   So the names should be either `panelFillProperty` and `panelFill`, or `panelColorProperty` and `panelColor`. 

Creating a new lint rule for this might be good.

**Comment by matthew-blackman** [comment]
Thanks for the review @pixelzoom. This has been updated in the commit. A lint rule would not be a bad thing to have here. @pixelzoom can you provide feedback on the way we're using the mysteryLauncherFillColorProperties array, and whether this can be closed?
