### ISSUE TITLE
Combine common directories.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#197]
Related to #32 ...

I understand from implementation-notes.md that VSM is “Variability, Sources, and Measures screens”.  And I suspect that SM is “Sources and Measures screens”, though it's not mentioned in implementation-notes.md.  That said...

Most repos have a single common/ directory, with the convention that anything used in > 1 place goes in common/.   And in fact the CRC says:

> For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory.

This sim is a little odd in that it has no common/, but has common-vsm/ and common-sm/.   This approach feels unnessary and not generally scalable. If you had something only used in Variability and Sources screens, would be created a 3rd common directory, common-vs/ ?  And if something is shared by Variability and Sampling screen, then what? -- you've already used common-vs.  You also have file prefixes "VSM" and "SM" that seem to identify related screens.

So... I recommond combining  common-vsm/ and common-sm/ into common/.  You might want to solicit a couple of other opinions on this.

**Comment by pixelzoom** [comment]
From the CRC:

> For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory.

**Comment by pixelzoom** [comment]
Subdirectories under a single common/ directory would probably accomplish what you want. But “vsm”, “sm”, etc. needs to be spelled out somewhere.

**Comment by pixelzoom** [comment]
If you decide to keep common-vsm and common-sm in https://github.com/phetsims/projectile-data-lab/issues/197, or move them to subdirectories of common/, you might also say something about them in implementation-notes.md (correspondence to "VSM" and "SM", what value they are providing, etc.)

**Comment by samreid** [comment]
@matthew-blackman let's discuss how to proceed.

**Comment by samreid** [comment]
We updated the documentation, closing.
