### ISSUE TITLE
Document non-standard file prefixes in implementation-notes.md.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#198]
Related to code review #32 ...

From the CRC:
>  - [ ] Do filenames use an appropriate prefix?  ...

There are a number of files with "VSM" and "SM" prefixes.  Non-standard prefixes should be documented somewhere, implemenation-notes.md looks like the intended place, but it's incomplete -- it identifies "VSM" but not "SM".  I'm not sure if there are other such prefixes, because I'm partway through the review.

If you decide to keep common-vsm and common-sm in https://github.com/phetsims/projectile-data-lab/issues/197, you might also say something about them in implemenation-notes.md (correspondence to "VSM" and "SM", what value they are providing, etc.)

**Comment by matthew-blackman** [comment]
The commit looks good to me and adds the appropriate amount of documentation. Nice work! Closing.
