### ISSUE TITLE
Review eslintConfig in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#200]
Related to code review #32 ...

From the CRC:
> Does package.json include any config that was only needed for development? For example: ...

`eslintConfig` looks like it needs some cleanup, sometime before the sim is published.

**Comment by samreid** [comment]
package.json eslintConfig currently looks like this:

```json
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "overrides": [
      {
        "files": [
          "**/*.ts"
        ],
        "rules": {
          "@typescript-eslint/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": true,
              "ts-ignore": true,
              "ts-check": true,
              "ts-nocheck": true
            }
          ],
          "no-object-spread-on-non-literals": "error",
          "additional-bad-text": [
            "error",
            {
              "forbiddenTextObjects": [
                "dispose"
              ]
            }
          ],
          "author-annotation": "error"
        }
      }
    ]
  }
```

What do you recommend we change?

**Comment by pixelzoom** [comment]
I said it should be reviewed and cleaned up.  For example, "no-object-spread-on-non-literals": "error" and `"author-annotation": "error"` are both unnecessary, because they are the defaults in chipper's .eslinrc.js.

**Comment by samreid** [comment]
Thanks! I checked each entry and saw that the two you mentioned are unnecessary. The other ones seem necessary. So I removed the redundant ones. Closing.
