### ISSUE TITLE
"This Property" vs "This property" in phetioDocumentation.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#201]
For code review #32 ...

I've mostly given up pointing out the difference between Property (uppercase) and property (lowercase), because I get the vibe that no one agrees that it's important, and because pointing it out hasn't changed anything. There are plenty of examples in code comments for this sim that I'm not going to report (or did I just report them? :)

But `phetioDocumentation` is public facing, and this sim contains a mixture of "This Property..." (correct) and "This property..." (incorrect).  So whether you agree with whether Property vs property is significant, it seems worth choosing one and using it thoughout `phetioDocumentation`.  I recommend choosing "This Property...".

**Comment by pixelzoom** [comment]
One other thought.... You could avoid the entire issue by omitting the "This Property" bit, like this example for PDLModel `singleOrContinuousProperty`:

```diff
      phetioDocumentation: 'This property indicates whether the launcher is in single or continuous launch mode.',
      phetioDocumentation: 'Indicates whether the launcher is in single or continuous launch mode.',
```

**Comment by samreid** [comment]
Before starting, there are 162 occurrences of "Property" (capitalized) in the project. I will review all the lowercase ones and see which need to be promoted.

**Comment by samreid** [comment]
After the commit, there are 197 occurrences of "Property", so I upconverted 35 cases. 

> One other thought....

We felt that the complete sentences were nice here, so I kept them. Everything else seems good. Closing.
