### ISSUE TITLE
Noncomplicance with CRC requirements for dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#202]
For code review #32 ...

implementation-notes.md says:
> * Objects are not dynamically allocated, and are instead statically allocated.

... so presumably nothing needs to be disposed, and I can confirm that I see no calls to `dispose`. 

But this sim is technically not in complicance with this CRC item:

> - [ ] All classes that do not properly override dispose should either (a) use `isDisposable: false`, or (b) implement
a `dispose` method that calls `Disposable.assertNotDisposable`. 

I see only 3 occurrences of (a) and zero occurrences of (b) in the entire code base.

Imo, this CRC item is essential in common code or in a sim that disposes some things, but not others.  It's less important in a sim like this that disposes of nothing -- unless it might use dispose in the future?   So... Up to you whether to do anything here.

**Comment by pixelzoom** [comment]
.... and yes, I see this in package.json:

```
              "forbiddenTextObjects": [
                "dispose"
              ]
```

**Comment by samreid** [comment]
@matthew-blackman let's discuss this

**Comment by samreid** [comment]
Thanks, @matthew-blackman and I agreed to document this as prescribed above. Closing.
