### ISSUE TITLE
Dynamic layout issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#204]
For code review #32, CRC item:

> - [ ]  Does the sim behave correctly with dynamic layout, to support dynamic locale? Run with `stringTest=dynamic` and
use the left/right arrow keys.

Overall the sim looks great. But I did find 3 problems.

(1) In the Histogram, the "Bin width" ComboBox overlaps the "Distance" x-axis label:

<img width="744" alt="screenshot_3058" src="https://github.com/phetsims/projectile-data-lab/assets/3046552/3d8fa254-363d-4ebe-a1c6-7060e390293e">

(2) In the field display, "No data" does not remain centered:

<img width="305" alt="screenshot_3060" src="https://github.com/phetsims/projectile-data-lab/assets/3046552/8b3db392-2bbc-4510-a07d-29bbc4188fb4">

(3) In TimeControlNode, both the text and the radio buttons are scaled down. Only the text should scale; the radio buttons should not change size.  The buttons should also remain vertically centered on the play/pause button.  This is likely a problem in TimeControlNode, and a fix would benefit all sims.

<img width="188" alt="screenshot_3059" src="https://github.com/phetsims/projectile-data-lab/assets/3046552/dc8b90df-5eb2-433c-bffb-9b7ddba7ea1b">

**Comment by samreid** [comment]
I fixed the histogram overlap. 

> (2) In the field display, "No data" does not remain centered:

This one is only a problem in the Sampling screen. I could use @matthew-blackman help on that layout.

I wonder if the TimeControlNode issue is related to https://github.com/phetsims/scenery-phet/issues/826 which @marlitas was asking about.

**Comment by matthew-blackman** [comment]
Self-assigning to work on the Sampling field sign.

**Comment by samreid** [comment]
The proposed commit fixes the problem in my testing. @matthew-blackman can you please test? Feel free to close if the behavior is correct.

**Comment by matthew-blackman** [comment]
@samreid and I reviewed the changes here and everything looks great. Tested and all known layout issues are fixed. Nice work! Closing.
