### ISSUE TITLE
Add sounds for Sample Size Button Options

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/projectile-data-lab#206]
I have added 4 sounds

- pdlSampleSize40.mp3
- pdlSampleSize15.mp3
- pdlSampleSize5.mp3
- pdlSampleSize2.mp3

**Comment by samreid** [comment]
@matthew-blackman is working on this, so I will self-unassign.

**Comment by Ashton-Morris** [comment]
@matthew-blackman I am adding theses sounds we discussed in todays meeting now.

- pdlSampleSize40v2.mp3
- pdlSampleSize15v2.mp3
- pdlSampleSize2v2.mp3

**Comment by matthew-blackman** [comment]
During the 3/1 sound design meeting, @emily-phet @Ashton-Morris and I iterated on the sounds for sample sizes 2, 15 and 40. We shortened the longer sounds to make them more UI-friendly. I added the latest to the sim and they sound great. Nice work all! Closing.
