### ISSUE TITLE
Add sounds for the projectile selection buttons/icons

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/projectile-data-lab#207]
I have added these sounds to our folder.

- pdlProjectileSelectionCannonBall.mp3
- pdlProjectileSelectionPiano.mp3
- pdlProjectileSelectionPumpkin.mp3

Edit: I remembered that it was discussed that they might sound good with a filter on them, these are the same files with a low pass filter.

- pdlProjectileSelectionCannonBallLPF.mp3
- pdlProjectileSelectionPumpkinLPF.mp3
- pdlProjectileSelectionPianoLPF.mp3

**Comment by samreid** [comment]
@matthew-blackman is working on this, so I will self-unassign.

**Comment by matthew-blackman** [comment]
This was reviewed/approved in the 3/1 sound design meeting. Nice work all! Closing.
