### ISSUE TITLE
Switching sample cards while launching is buggy

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#21]
Let's fix it!

To reproduce:
- Go to Sampling screen
- Increase sample size to 15 or 40
- Launch
- While projectiles are being created, navigate to other sample cards

Result:
<img width="834" alt="Screen Shot 2023-12-22 at 12 17 16 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/bb554db7-9dc0-4603-92c7-03a4b5799d42">

**Comment by samreid** [comment]
I feel this is fixed except for showing an undesired cannon flame image. @matthew-blackman is that correct?

**Comment by samreid** [comment]
If I recall correctly, we also discussed in Friday's design meeting that when you are viewing an older sample or projectile card, and a new one lands, we do not automatically jump to the end. Right?

**Comment by samreid** [comment]
> If I recall correctly, we also discussed in Friday's design meeting that when you are viewing an older sample or projectile card, and a new one lands, we do not automatically jump to the end. Right?

That was changed so we do automatically jump to a new one when it lands.

The solution for this issue will be to gray out the sample selector buttons while any projectile is in the air.

**Comment by matthew-blackman** [comment]
@catherinecarter can you weight in on the desired behavior here? Specifically:

- Should the user be allowed to use the sample selector buttons during a single sample or while continuous sampling?
- If yes to above, if the user click on the sample selector buttons during a single/continuous launch, what should happen?

**Comment by catherinecarter** [comment]
I think the left/right scroll should behave like the previous screens where, when sampling, the scroll buttons should be inactive. The user needs to wait until sampling has completed to be able to scroll between any previously taken samples.

**Comment by samreid** [comment]
@matthew-blackman and I committed this feature above.  We would like to consider this while working on #91, and corner cases.

**Comment by matthew-blackman** [comment]
The sample selector buttons have been disabled while launching a sample or continuous sampling. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
