### ISSUE TITLE
Consider renaming PDLPanelSection subclasses.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#211]
For code review #32 ...

The names of `SectionLauncherConfiguration`, `SectionMysteryLauncher`, and `SectionProjectileType` are a little odd.  They all extend `PDLPanelSection`, so they would typically be named `SomethingSection` or `SomethingPanelSection`.

Use sites are also a little odd, where `const` names do not match class names (same words, but different order). E.g.:

```ts
const launcherConfigurationSection = new SectionLauncherConfiguration(...
```

Consider renaming to `LauncherConfigurationSection`, etc. where the word "Section" is last.  This would match the superclass name and the `const` instance names.  E.g.:

```ts
export default class LauncherConfigurationSection extends PDLPanelSection { ...

const launcherConfigurationSection = new LauncherConfigurationSection( ...
```

**Comment by matthew-blackman** [comment]
This was addressed in commit https://github.com/phetsims/projectile-data-lab/commit/d9ed4efe64718c604f2dcc39e2df08acc99ea6bb. Not sure why it's not linking over here. Thanks for the suggestion @pixelzoom, this looks much cleaner. Changes were straightforward. Closing.
