### ISSUE TITLE
Undesirable workaround for Audio preferences.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#215]
For code review #32 ...

In projectile-data-lab-main.ts, a blank Node is being created for the left column of the Audio preferences tab, to workaround a joist layout problem -- see relevant code below.  Rather than creating an undesirable dependency on bad layout behavior, it would be preferrable to fix the layout problem in joist.  Or at least open a GitHub issue for the problem, with a TODO here, so that the problem may eventually get fixed, and someone will know to remove this workaround.

```ts
    audioOptions: {
      customPreferences: [
        {

          // Due to the layout considerations in the Preferences Dialog, it has 2 columns. Our entry for the left column
          // is blank
          createContent: () => new Node()
        },
        {
        createContent: tandem => new AudioPreferencesContentNode( tandem.createTandem( 'audioPreferences' ) )
      } ]
````

**Comment by pixelzoom** [comment]
The conclusion was:
* Open a joist issue for improving the `audioOptions.customPreferences` API, so that this type of workaround is not needed.
* Leave the workaround in place. Add a TODO comment that links to the joist issue, so that future improvement of  the API will also address the workaround in PDL.

**Comment by samreid** [comment]
I opened the Joist issue and pointed TODOs at it. Closing.
