### ISSUE TITLE
Incorrect options types for subclasses of VSMScreenView

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#216]
For code review. #32...

For example, in VariabilityScreenView.ts: 

```ts
type ProjectileDataLabScreenViewOptions = SelfOptions & ScreenViewOptions;
...
export default class VariabilityScreenView extends VSMScreenView<VSMField> {
...
const options = optionize<ProjectileDataLabScreenViewOptions, SelfOptions, ScreenViewOptions>()( {}, providedOptions );
```

Every occurence of `ScreenViewOptions` should be `VSMScreenViewOptions`, because the superclass is `VSMScreenView`.

`ProjectileDataLabScreenViewOptions` should be `VariabilityScreenViewOptions`.

**Comment by pixelzoom** [comment]
Also note that `type ProjectileDataLabScreenViewOptions` is used in every subclass of `VSMScreenView`, which looks like a copy-paste error.

I went ahead an fixed this. @samreid or @matthew-blackman please review, close if OK.

**Comment by pixelzoom** [comment]
One more minor change in . `& WithRequired<PDLScreenViewOptions, 'tandem'>` is redundant, simplified to `& PDLScreenViewOptions,`.

**Comment by matthew-blackman** [comment]
Good find @pixelzoom - changes look good and thanks for fixing. Reviewed and closing.
