### ISSUE TITLE
Various problems with options types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#219]
For code review #32 ...

In addition to problems noted in https://github.com/phetsims/projectile-data-lab/issues/216, there are a whole bunch of problems related to options types, including...

* type names that don't match their associated class, e.g. MeasuresScreen and ProjectileDataLabScreenOptions
* parent options type that does not match the superclass
* swapped parameters to optionize (<Parent,Self,Provided> instead of <Provided,Self,Parent>)
* missing uses of WithRequired<..., 'tandem'>
* redundant usees of WithRequired<..., 'tandem'>
* etc.

It will be easier for me to fix these than to enumerate them.

**Comment by pixelzoom** [comment]
I fixed many problems in https://github.com/phetsims/projectile-data-lab/commit/d01f7e204729ac3354d5646898fde4b2cc0983bb.  There are probably more. Over to @samreid or @matthew-blackman to review.

Note that I did not do any narrowing of options types, nor will I open an issue about it, because I know that @samreid and I disagree on that.  But I will note that there are many options types that are overly broad, sometimes dangerously broad -- allowing a client to blast something that is the responsibility of the associated class, and should not be part of the class' options API.

**Comment by matthew-blackman** [comment]
I went through each usage of optionize and checked that the correct options patterns were being applied. I caught 2 more cases that are fixed in the commits. I don't see any further work to be done here. Feel free to reopen if more errant options types pop up. Closing.
