### ISSUE TITLE
Sampling screen is buggy when interacting during a sample

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#22]
In the current state, the sampling screen is behaving mostly correct, with the following desired behavior:

Single sample: Launches projectiles in sample, delay after last projectile landing before showing the mean
Continuous sampling: Showing the sample and mean together, with rapid collection of samples

The interactions that are still popping up occur when the user performs one of the following actions while a sample is forming:

1) Switching between 'Single' and 'Continuous' mode
2) Navigating to a previous sample
3) Hitting the launch button again

**Comment by samreid** [comment]
Some notes from the google doc:

* Sampling screen - Preliminary QA testing for edge cases
* Single sample behavior when hitting buttons mid-sample
* What if you change the launch mode radio button group? Should it autocomplete a sample? Or only if you subsequently press “launch”?
* Clear/reset/change selection/change mode (single vs continuous)

**Comment by matthew-blackman** [comment]
Let's hold off working on this until the behavior in #91 is finalized.

**Comment by matthew-blackman** [comment]
This is no longer relevant since the sample selector is disabled while launching or continuous sampling. Closing.
