### ISSUE TITLE
Avoid non-standard abbreviations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#220]
For code review #32 ...

From the PhET coding conventions:

> - [ ] Names (types, variables, properties, Properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. For example: ...

There are dozens of occurrences of the `t` abbreviation, like:

```ts
      derive: t => t.launcherProperty,
```

Sometimes `t` is a launcher, sometimes `t` is a field.  All of these occur in the context of a relatively unusual use of DynamicProperty, and `t` doesn't make understanding that any easier.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/projectile-data-lab/commit/f269a55ec25131b4c17760a63c054b5720980104, I replaced `t` with `field` or `launcher`, as appropriate.

I search for 'const ', 'let ', and ' => ', and skimmed the results.  I don't see any other abbreviations.

Over to @samreid or @matthew-blackman to review, close if OK.

**Comment by samreid** [comment]
Excellent, thanks for correcting this. Closing.
