### ISSUE TITLE
VSMField resets field owned by superclass Field.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#221]
For code review #32 ...

VSMField is currently resetting `angleStabilizerProperty`, which is owned by superclass Field:

```ts
  public override reset(): void {
    super.reset();

    this.angleStabilizerProperty.reset();
    this.continuousLaunchTimer.reset();
  }
```

Why is `angleStabilizerProperty` not being reset in Field `reset`?  If there a good reason, document.  Otherwise move it.

**Comment by samreid** [comment]
Good recommendation. @matthew-blackman and I moved it to the parent class and it seems better. Closing.
