### ISSUE TITLE
REVIEW comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#225]
For code review #32 ...

This issue is a catch-all for commiting REVIEW comment, and for any misc changes that I might make.

I'll assign this issue to @samreid and @matthew-blackman when I've completed the review.

**Comment by samreid** [comment]
I'm planning to address a few of the REVIEW issues that have already been written.  Co-assigning for now.

**Comment by pixelzoom** [comment]
I have completed review comments, search for "REVIEW".  Over to @matthew-blackman and @samreid.

**Comment by matthew-blackman** [comment]
All review comments have been addressed. Nice work @samreid and thanks for the recommendations @pixelzoom. This issue can be closed.
