### ISSUE TITLE
Disable the launch UI when the maximum amount of data is reached

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#23]
This includes the launch button and launch mode controls on all four screens.

**Comment by samreid** [comment]
I worked on this in https://github.com/phetsims/projectile-data-lab/commit/0a58b8c904918c8be053be81948f9ceb40d2c638 and https://github.com/phetsims/projectile-data-lab/commit/7f13f8e565646b22e84b0f1457aa70c6bf876c91

**Comment by samreid** [comment]
Sharing the reasoning for the latter commit. The "all done" phase should look exactly like the "showing samples with mean" phase, so that added duplication. Also, we cannot use the "all done" phase to decide when to disable the button, because it should disable when we have *started* too many samples rather than *completed* too many samples.

**Comment by samreid** [comment]
I committed a fix for VSM as well. However, there was a bad interaction with autofire, and I wrote:

> // TODO: Putting true here is buggy. When you launch out the max manually, the press clear, the button automatically is in auto-fire mode. See https://github.com/phetsims/projectile-data-lab/issues/7

@matthew-blackman and I should check in about this.

**Comment by samreid** [comment]
From the google doc:

> When continuous sample reaches max, should not be a grayed out “stop” button.

**Comment by samreid** [comment]
Should we add a query parameter to limit the number of projectiles and samples, to make it easier for us as QA to test?

**Comment by samreid** [comment]
In slack, we agreed to go with `&maxProjectiles=20&maxSamples=20` which is very clear even though kind of verbose. I'll work on that.

**Comment by samreid** [comment]
OK I added the query parameters and confirmed they are working. Next it would be good to collaborate on the steps listed above.

**Comment by samreid** [comment]
@matthew-blackman and I reviewed the behavior, everything looks good. These 2 recommendations are at odds:

* On pressing clear on VSM, continuous mode should resume
* On the max number of projectiles on VSM continuous, it should not show a "stop" button icon.

@matthew-blackman wants to put more emphasis on the first bullet point. In my opinion, the amount of time a student spends on the 500 projectile state would be very low and the icon doesn't matter that much.

**Comment by matthew-blackman** [comment]
After discussing with @catherinecarter, we agreed to set isContinuousLaunching as false when the maximum amount of data is reached. This will preserve the appearance of the most up-to-date 'launch mode' being maintained when the user clears the field.

**Comment by matthew-blackman** [comment]
The behavior is looking great! Closing.
