### ISSUE TITLE
CODAP wrapper: Environment should be save/loadable in CODAP file

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#232]
Note: We would also like to save/load the simulation state if possible.

**Comment by samreid** [comment]
Perhaps the documentation at https://github.com/concord-consortium/codap/wiki/CODAP-Data-Interactive-Plugin-API#interactivestate will help

**Comment by samreid** [comment]
There is a project at https://github.com/concord-consortium/codap-plugin-api that looks like it provides support for saving/loading the state and configuration.  I looked to see if we could adapt its pattern in our existing wrapper, but it was unclear. We could try porting our wrapper to use that plugin-api and see if it helps.

**Comment by samreid** [comment]
@matthew-blackman and I got this working yesterday. I improved the state handling logic and committed a working version. This should be reviewed and tested, and we will need to know whether to implement this for the tool data wrapper as well.

**Comment by matthew-blackman** [comment]
@catherinecarter @samreid and I reviewed this and everything is working well in our testing. The save/load, copy and 'shared view' features are all supported by the wrapper. This includes the simulation state, the checkboxes and the CODAP data. Closing.
