### ISSUE TITLE
Angle stabilizer slider not updating with keyboard input

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#235]
@samreid mentioned that this could be caused by the keyboard increment being less than the snap increment for the slider. Let's investigate and fix.

**Comment by matthew-blackman** [comment]
@catherinecarter this is ready for review. As suspected, it was being caused by the snapping. I set the keyboard increment to align with the tick marks on the slider, with the Shift modifier allowing half-tick increments. I think it's working well and it seemed like a good idea to give Shift key more fine-tuned control, even within the snapping behavior. Feel free to close if all passes review.

**Comment by catherinecarter** [comment]
The left/right arrows are working well, the WASD keys are not working.

Also, I agree the Shift+arrows is nice to go in smaller increments. The end/home is also working nicely.

The page up/down is confusing. Usually the page up/down steps in larger steps than the left/right arrows(like the interval tool), but in this case, it's acting like the shift key and instead is moving in smaller steps. 

I recommend having the page up/down go between two tick marks (end, middle, end), and leave the current left/right and shift+arrow as is.

The page up/down behavior will also need to be added to the keyboard help dialog box.

**Comment by samreid** [comment]
> The left/right arrows are working well, the WASD keys are not working.

Thanks, I moved that to a sun-specific issue.  Next I will work on the page up/down issues.

**Comment by samreid** [comment]
For the angle stabilizer slider, I fixed the pgup/pgdwn and added this help section:

<img width="643" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/e4a97b41-217b-4781-a549-383f303a12da">

We will adjust the layout in https://github.com/phetsims/projectile-data-lab/issues/239. Closing.
