### ISSUE TITLE
CODAP wrapper: caseIndex is incorrect when autogenerating data

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#236]
This is being caused by the shortcuts being used to optimize performance when autogenerating data. Let's see if we can fix this without disrupting the autogenerate performance. I discussed this with @catherinecarter, and we agreed that having faster performance for autogenerating data is more important than having a separate caseIndex column in CODAP. She was able to quickly demonstrate another option available within CODAP - creating a column equivalent to caseIndex by using the column tools.

**Comment by samreid** [comment]
@matthew-blackman and I solved this in https://github.com/phetsims/projectile-data-lab/issues/234 via an await. Closing.
