### ISSUE TITLE
Rendering problems during pan/zoom

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#237]
@matthew-blackman and I have seen rendering artifacts during pan/zoom.

For example:

The navigation bar is gone:

<img width="1622" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/69fa917e-e941-453d-8499-a07039555c9d">

Some buttons and thumbnails are missing:

<img width="2039" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/e2ffd893-837c-4fbd-952c-d5136f0d7340">

**Comment by samreid** [comment]
@jessegreenberg or @jonathanolson any ideas what is happening?

**Comment by zepumph** [comment]
@jonathanolson and I were able to easily reproduce this problem this morning. Only on chrome, but it can be pretty horrible. (noting this is the same problem as https://github.com/phetsims/scenery/issues/1507).

**Comment by jonathanolson** [comment]
Hey, just saw this was still open. I think it was resolved as part of https://github.com/phetsims/scenery/issues/1507, can you check?

**Comment by samreid** [comment]
Looks great! Nice work. No problems noted. Closing.
