### ISSUE TITLE
Add preference for turning off the landing sound?

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#238]
In the preferences menu, currently there are options to change the sound of the launched projectile. One of these options is "none," meaning you can turn the sound off for the launcher. 

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/ea2e5efe-1ea1-41cf-ad8a-f4e5997a2784)

There is no option to turn the landing sound off. It seems unbalanced to be able to turn off the launcher sound and only hear the landing sound, but no option to turn off the landing sound and only hear the launcher sound.

I'm wondering if there are others who agree that adding the option to turn the landing sound off would feel more balanced.

**Comment by matthew-blackman** [comment]
I consulted with @emily-phet and @Ashton-Morris about this, and their recommendation was to omit this feature - at least until there is further evidence that it is needed. Their reasoning was that projectile landing sounds are central to the distribution of the data in the histogram, which is a core feature to the sim's learning goals. Allowing users to silence this seemed less productive than allowing them to silence the launch sound to focus on the distribution of positions.

Currently, users can hear the launch sound by itself if they hit launch a few times manually - and could hear the launch sounds by themselves in the time before the first projectile hits the ground. This seems reasonable to me.

@catherinecarter does this reasonable to you? This would be a low-cost feature to implement if we decide it is warranted, but I tend to agree with the reasons above in leaving it out unless it is requested.

**Comment by samreid** [comment]
In today's discussion, we agreed to go forward with implementing this.

**Comment by catherinecarter** [comment]
The sounds seem to be working as intended, which is great. 

The layout of the preferences menu is a little squished, though. I don't know how it works, but if the "Play Landing Sound" can be shifted down just a tad to create a buffer between the launch sound description and it, I think it would be more readable.

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/07b3d5e8-40fe-46dc-a600-9fce815b527e)

**Comment by matthew-blackman** [comment]
Updated in the commit - @catherinecarter feel free to close if the updated version looks good.

**Comment by catherinecarter** [comment]
Looks easier to read. Nice.
