### ISSUE TITLE
Memory Leak Testing

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#24]
I saw a TODO about a likely memory leak, and wanted to test.

This test in in Chrome with unbuilt on main:

after 30 second fuzzing: 147MB
after 2 minutes fuzzing: 170MB
3 minutes and 30 seconds: 196MB

So it is likely we have memory leaks.

**Comment by samreid** [comment]
After some trial fixes:

30 seconds: 147MB
60 seconds: 149MB
6 minutes: 162MB

So it seems better, but probably still more to do.

I committed https://github.com/phetsims/projectile-data-lab/commit/c72080b11f160e20d8edad0a238aa63957d02d3d

**Comment by samreid** [comment]
Running a new test on a phet-brand version built via `grunt --brands=phet --minify.mangle=false`.  Fuzzing.

1 minute: 125MB
2 minutes: 124MB
3 minutes: 129MB
4 minutes: 129MB
5 minutes: 128MB

So this is looking OK.

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/2961d00c-e762-4bf5-96a7-ec5e305fecb8)

**Comment by samreid** [comment]
Today fuzzing phet-io brand locally (macbook air):

10 sec: 164MB
1 minute: 161MB
2 minutes: 174MB
3 minutes: 192MB
4 minutes: 190MB
6 minutes: 194MB
7 minutes: the browser is taking a long time to compute it

Let's start another run:

**Comment by matthew-blackman** [comment]
Today fuzzing phet-io brand locally (macbook pro M1 Pro):

0 minutes: 158MB
8 minutes: 179 MB
26 minutes: 199 MB
37 minutes: 221 MB

**Comment by samreid** [comment]
I believe this DerivedProperty in LauncherNode.ts is leaking:

```ts
  protected updateMysteryLauncher( mysteryLauncherNumber: number, isIcon = false ): void {
    this.launcherBarrelGraphics.children = this.launcherBarrelGraphicsForType( mysteryLauncherNumber, isIcon );
    this.launcherFrameBack.children = this.launcherFrameBackGraphicsForType( mysteryLauncherNumber, isIcon );
    this.launcherFrameFront.children = this.launcherFrameFrontGraphicsForType( mysteryLauncherNumber );
  }

  private updateLauncherHeight( height: number ): void {
    this.y = this.modelViewTransform.modelToViewY( height );
  }

  private launcherBarrelGraphicsForType( mysteryLauncherNumber: number, isIcon: boolean ): Node[] {
    const barrelColorProperty = PDLColors.mysteryLauncherFillColorProperties[ mysteryLauncherNumber - 1 ].barrel;
    const barrelDarkColorProperty = new DerivedProperty( [ barrelColorProperty ],
      color => color.darkerColor( 0.8 ) );
```

We probably need to add a way to persist/reuse or dispose those `barrelDarkColorProperty` instances.

**Comment by samreid** [comment]
Fixed in the commit. These snapshots are over a roughly 30 minute time:

<img width="201" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/373289d8-5609-490e-ae72-9dad7ae1964d">
