### ISSUE TITLE
Move 'Basic Actions' to the end of they keyboard help dialog

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#250]
@terracoda recommended that we move the 'Basic Actions' section to the end of the keyboard help dialog on each screen. The order is as follows:

1. Top left
2. Bottom left
3. Top right
4. Bottom right

Let's implement these changes to improve the layout of the keyboard help dialog.

**Comment by terracoda** [comment]
Just adding the reasoning:

when linearized for reading from top to bottom in one column we want the Basic Actions (the actions learners are most likely to know from general use) to be last. Important sim-specific or custom actions should come first.

**Comment by matthew-blackman** [comment]
Everything looks good here. Thanks all! Closing.
