### ISSUE TITLE
CODAP wrapper: Column names should not use camel case

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#251]
For the variable column names, the other CODAP examples use separate words with capitalized letters. For example, 'horizontalDistance' should be 'Horizontal Distance'. Let's maintain this norm for variables in the CODAP wrapper.

**Comment by samreid** [comment]
I converted the wrapper to use first word uppercase, second word lower case, and used it pervasively. I wasn't sure exactly where to do this mapping, but right now it is very upstream. @matthew-blackman can you please review/test?

**Comment by matthew-blackman** [comment]
@catherinecarter @samreid and I reviewed this and agreed on the 'separate words, first letter of first word capitalized, first word of subsequent letters lowercase' design. Nice work! Closing.
