### ISSUE TITLE
Angle Stability - Update PhET-IO API to use new name and min/max

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#252]
The work done in https://github.com/phetsims/projectile-data-lab/issues/249 is looking great, and we should make sure that the PhET-IO API is consistent with the new naming convention. In studio, users should see 'Angle Stability' in cases where they are adjusting this slider, or looking at the properties of the mystery launchers.

Note: I don't think it is necessary to change the code that refers to the 'angle stabilizer'. This is an implementation detail, and we can consider the mechanism as the 'Angle Stabilizer', but the customizable variable is the 'Angle Stability'.

**Comment by samreid** [comment]
Note I already started using "Angle stability" terminology in the codap wrapper.

**Comment by samreid** [comment]
OK I renamed the variables, keeping "Angle stabilizer" where appropriate. I renamed variables or classes where appropriate.  @matthew-blackman can you please review and clarify what should be done about min/max?

**Comment by matthew-blackman** [comment]
Reviewed and it looks like all references to angle stability are consistent with the UI. Nice work! Closing.
