### ISSUE TITLE
barBlockSwitch doesn't reset with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#254]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1060, on all screens: if I toggle the barBlockSwitch in the histogram accordion box, it doesn't switch back to the default with Reset All.

**Steps to reproduce**
1. On an screen, toggle the barBlockSwitch to bars
2. Press Reset All

**Visuals**

https://github.com/phetsims/projectile-data-lab/assets/87318828/724fe67f-8951-4325-a10e-c4195aa41ea7

<details>

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Projectile Data Lab‬
URL: https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.22/phet/projectile-data-lab_all_phet.html
Version: 1.0.0-dev.22 2024-03-18 16:30:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
Language: en-US
Window: 1393x699
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by matthew-blackman** [comment]
Nice find @Nancy-Salpepi! This has been fixed in the commit. Labeling ready for review.

**Comment by Nancy-Salpepi** [comment]
starting you off with a softball...haha

**Comment by Nancy-Salpepi** [comment]
Looks fixed on main. Closing!
