### ISSUE TITLE
Items missing from Keyboard Help Dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#257]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1060, it looks like some items are missing from the Keyboard Help dialog:

EDIT: SORRY! I was on the wrong screen when looking for slider controls. I deleted that section.

2. For first 3 screens: To select first or last projectile use `home` `end` 
    For the last screen: To select first or last sample set use `home` `end` keys

If I see any others I will continue to add to this issue.

**Comment by Nancy-Salpepi** [comment]
Also need a section for the combobox (Bin Width or Total Bins). Something similar to this but making it specific to PDL:
<img width="357" alt="Screenshot 2024-03-18 at 4 47 16 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/39b946b7-b3d3-4ce1-a4b9-af1744d59b8d">

**Comment by Nancy-Salpepi** [comment]
Related to https://github.com/phetsims/projectile-data-lab/issues/255, I see that when ONLY the increment button has keyboard focus, if I press the right arrow key, the sim will go through all of the projectiles (or samples). The same for when ONLY the decrement button has focus. If that was intentional, that would also need to be added to the Keyboard Help dialog.

**Comment by samreid** [comment]
Where should these new sections go? Should we shrink down other things to make room?

<img width="1874" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/b2c94fad-27b7-490c-899e-d7ea897e6fe9">

**Comment by matthew-blackman** [comment]
@Nancy-Salpepi does every UI context need its own section? We reviewed the keyboard dialog with @terracoda and she didn't mention any issues with the current layout. Could the combo box and projectile/sample selector could be considered part of the 'Basic Actions' section?

The keyboard help dialog is getting a bit overloaded with information that is all starting to look similar. Can we limit the amount of duplicated or similar info and keep it from getting out of hand?

**Comment by terracoda** [comment]
Up to this point in sim design, the keyboard help dialogs have been fairly exhaustive, but the number of control-types has been much lower. Space issues are creeping in as we add Alternative Input to sims with a larger sets of diverse interactions. Screen 3 in this sim is off the charts in terms of control types when you check all the checkboxes.

I think we discussed the combobox and it was determined not to be an interaction essential for learning, so we opted to not include it. Do you remember this conversation @matthew-blackman?

The combobox is a fairly standard interaction and may not pose issues to learners new to using the keyboard. 

It could potentially be described on the first screen and not on subsequent screens, leaving space for the slider controls.

Or, Basic Actions could be put into a separate Tab in the dialog when the number of controls get numerous.

A Sim Actions and Basic Actions Tab would make the KB Shortcuts dialog more like the Preferences Menu. Maybe something to discuss?

Or we need a central resource for all sims and then only put sim-specific actions in the KB Shortctus dialog.

**Comment by terracoda** [comment]
This issue might need a design meeting?

**Comment by Nancy-Salpepi** [comment]
In my experience all keyboard actions have been in the dialog. If it has been decided not to do that, just let QA know. 
@terracoda is definitely the expert on this, so I am going to remove my assignment here.

**Comment by terracoda** [comment]
@Nancy-Salpepi, you are correct that the number of keyboard actions have been pretty exhaustive.

This sim and future complex sims pose space challenges to that approach.

The sim Ratio and Proportion has comboboxes on both screens, but there, due to space issues, we only provide instructions for the combobox on the first screen's KB Shortcuts dialog.

@matthew-blackman, do you think that could work?

**Comment by matthew-blackman** [comment]
4/3 meeting:
@terracoda recommends adding a dialog for ComboBox to the first screen's keyboard help, since it has available space in the help dialog. Let's customize it to give as much specificity as possible while still making sure it applies to both the 'Bin width' and 'Number of bins' paradigms.

We'd like to open up a conversation about streamlining the keyboard help dialog in general. @terracoda mentioned the possibility of having a 'General Actions' section that applies to common UI components, as well as a 'Sim-Specific' section.

**Comment by samreid** [comment]
@matthew-blackman and I added the "Histogram Bin Controls" to screens 1,2,4. Closing.
