### ISSUE TITLE
Time Controls overlap Field Sign with ?stringTest=X

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#258]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1060, with stringTest=X the Time Controls overlap the Field Sign on the Measures screen. I don't see this with any of the other stringTests. 

**Steps to reproduce**
1. Add ?stringTest=X to the end of the url
2. Go to the Measures Screen

**Visuals**
?stringTest=X (left) and ?stringTest=dynamic (right)

<img width="335" alt="Screenshot 2024-03-19 at 9 38 45 AM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/94921e44-d42f-4931-91ee-dcbf697855ac">     <img width="335" alt="Screenshot 2024-03-19 at 9 45 58 AM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/2be74bcb-5bcd-467d-a564-7e0076c544c9">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Projectile Data Lab‬
URL: https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-dev.22/phet/projectile-data-lab_all_phet.html
Version: 1.0.0-dev.22 2024-03-18 16:30:54 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
Language: en-US
Window: 1438x699
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
@matthew-blackman and I believe a maxHeight on the stopwatch icon may be throwing this off.  I'll take a look.

**Comment by samreid** [comment]
Fixed and working well, good discovery. Closing.
