### ISSUE TITLE
Fine-tune histogram thumbnail grid line thickness/spacing

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#26]

**Comment by samreid** [comment]
I'm not sure what is desired for this issue. @matthew-blackman or @catherinecarter can you please clarify?

**Comment by catherinecarter** [comment]
KF and I noticed that the gridlines are mildly distracting in the thumbnails due to them being smaller than the big histogram. Not sure what the solution is per se, but I believe some of them can be removed so the graph is easier to see and make sense of the small histograms. Perhaps we can ask for feedback on options in design meeting?

**Comment by matthew-blackman** [comment]
The devs discussed this with @catherinecarter and we reached the following consensus:

- X-axis scaling is working nicely with hard-coded values. We should revisit the exact values once the launcher properties and order have been finalized.
- Y-axis scaling is working nicely.
- The vertical grid lines (along the x-axis) are distracting, reduce the number of them.
- The horizontal grid lines (along the y-axis) should change with every zoom level. As the user zooms in, the lines should become more spaced out.

**Comment by matthew-blackman** [comment]
@catherinecarter can you provide values for the thumbnail grid lines?

- Number of vertical lines along the x-axis
- Number of horizontal lines along the y-axis using the following format:
```
export const ZOOM_LEVELS = [ {
  maxCount: 500,
  tickSpacing: 50
}, {
  maxCount: 200,
  tickSpacing: 20
}, {
  maxCount: 100,
  tickSpacing: 10
}, {
  maxCount: 75,
  tickSpacing: 15
}, {
  maxCount: 50,
  tickSpacing: 10
}, {
  maxCount: 25,
  tickSpacing: 5
} ];

**Comment by catherinecarter** [comment]
Before I suggest anything, can you help me understand how the minor grid lines are determined? It seems there are always 5 minor gridlines regardless of how many major tick marks there are.

The reason I ask is because for the 3 smaller zoom levels (maxCount = 25, 50, and 75), there are 5 major tick marks, and for the 3 larger zoom levels (maxCount = 100, 200, and 500), there are 10 major tick marks. So when zooming, you only visually notice the zoom level changing between maxCount = 75 and maxCount = 100.

I'm wondering if we can manipulate the minor gridlines to help show the change as well, or maybe instead, of manipulating the major tick marks?

Without being able to test out how this looks and I had to suggest something, I might try this:
```export const ZOOM_LEVELS = [ {
  maxCount: 500,
  tickSpacing: 20
}, {
  maxCount: 200,
  tickSpacing: 10
}, {
  maxCount: 100,
  tickSpacing: 10
}, {
  maxCount: 75,
  tickSpacing: 5
}, {
  maxCount: 50,
  tickSpacing: 5
}, {
  maxCount: 25,
  tickSpacing: 5
} ];

**Comment by samreid** [comment]
> Before I suggest anything, can you help me understand how the minor grid lines are determined? It seems there are always 5 minor gridlines regardless of how many major tick marks there are.

Yes, it seems so. The code is:

```ts
verticalGridLines.setSpacing( ZOOM_LEVELS[ this.zoomLevelProperty.value ].tickSpacing / 5 );
```

We can change that as desired.

**Comment by samreid** [comment]
I do not believe we can meet all of the following constraints at the same time:

* Labeled tick marks get progressively closer together as you zoom out.
* The top edge of the chart gets a tick mark
* The bottom edge remains at 0
* We have numbers like 25, 50, 75, 100, 200, 500

The problem is that the factors of those numbers do not scaffold in a way that lets us get that zoom out effect. I suspect we will eventually get rid of the top edge of the chart getting a labeled tick mark, since that will allow us to keep everything else sensible.  Before testing that, I wanted to see what it would look like if we gradually increased the number of vertical tick marks from 4 up to 10.  Choosing as natural-looking numbers as possible given that constraint and trying to match similar ranges as before, I ended up with:

```ts
export const ZOOM_LEVELS = [ {
  maxCount: 600,
  tickSpacing: 75
}, {
  maxCount: 350,
  tickSpacing: 50
}, {
  maxCount: 120,
  tickSpacing: 20
}, {
  maxCount: 50,
  tickSpacing: 10
}, {
  maxCount: 20,
  tickSpacing: 5
} ];
```

which looks like this:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/e6ba5ac7-48ff-47e8-a41a-7e2a1c032af8)

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/2842f008-ffeb-4cd4-b815-6de3b357ed4d)

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/d772f8ba-f2e5-48c7-ae5e-32fe5057d033)

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/5b093301-4850-43ca-afcc-375971e8f52d)

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/7fd54790-fbdd-433a-8d78-24d8aa6a7d9e)

In the commits, I also halved the number of grid lines in the thumbnails.

@matthew-blackman or @catherinecarter how would you like to proceed?

**Comment by catherinecarter** [comment]
I like the way the grid looks in the images you provided above, @samreid. I have a minor concern that increasing the number of major tick marks by 1 each time might not be enough to visually cue the user that the grid is being zoomed.

Maybe playing with the minor gridlines could couple with what you have above to accentuate the zoom level is changing? 

Also, maybe halving the horizontal grid lines along the y-axis wasn't the right call. The tick marks not being evenly spaced makes the thumbnails look unbalanced since there are 2 grid lines, making the space between them not symmetric when including the top and bottom of the graph box: 
<img width="170" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/9a3943c2-b5c9-4cda-8a12-c5087c28deae">

Can we adjust so there are 3 gridlines horizontally along the y-axis and the space between them (as well as the space above and below the top/bottom ones) are equal?

**Comment by samreid** [comment]
@catherinecarter and I investigated a configurable minor grid line spacing:

<details>

```diff

Subject: [PATCH] Add linked element for projectile selector, see https://github.com/phetsims/projectile-data-lab/issues/66
---
Index: js/common/view/HistogramNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/HistogramNode.ts b/js/common/view/HistogramNode.ts
--- a/js/common/view/HistogramNode.ts	(revision 0e0d8aab722771e942e1409b715b6f0f0cff4914)
+++ b/js/common/view/HistogramNode.ts	(date 1705085009468)
@@ -42,22 +42,28 @@
 
 export const ZOOM_LEVELS = [ {
   maxCount: 500,
-  tickSpacing: 50
+  tickSpacing: 50,
+  minorSpacing: 25
 }, {
   maxCount: 200,
-  tickSpacing: 20
+  tickSpacing: 20,
+  minorSpacing: 10
 }, {
   maxCount: 100,
-  tickSpacing: 10
+  tickSpacing: 10,
+  minorSpacing: 5
 }, {
   maxCount: 75,
-  tickSpacing: 15
+  tickSpacing: 15,
+  minorSpacing: 1
 }, {
   maxCount: 50,
-  tickSpacing: 10
+  tickSpacing: 10,
+  minorSpacing: 1
 }, {
   maxCount: 25,
-  tickSpacing: 5
+  tickSpacing: 5,
+  minorSpacing: 1
 } ];
 
 export default class HistogramNode extends Node {
@@ -298,7 +304,7 @@
       verticalTickLabelSet.setSpacing( tickSpacing );
       verticalTickMarkSet.setSpacing( tickSpacing );
       majorVerticalGridLines.setSpacing( tickSpacing );
-      verticalGridLines.setSpacing( ZOOM_LEVELS[ this.zoomLevelProperty.value ].tickSpacing / 5 );
+      verticalGridLines.setSpacing( ZOOM_LEVELS[ this.zoomLevelProperty.value ].minorSpacing );
       updateHistogram();
     } );
 

```

</details>

**Comment by samreid** [comment]
This is @catherinecarter's proposed recommendation. It keeps the same number of major tick marks and adjusts the minor gridline spacing:

<details>

```diff

Subject: [PATCH] Add linked element for projectile selector, see https://github.com/phetsims/projectile-data-lab/issues/66
---
Index: js/common/view/HistogramNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/HistogramNode.ts b/js/common/view/HistogramNode.ts
--- a/js/common/view/HistogramNode.ts	(revision 0e0d8aab722771e942e1409b715b6f0f0cff4914)
+++ b/js/common/view/HistogramNode.ts	(date 1705085866422)
@@ -42,22 +42,28 @@
 
 export const ZOOM_LEVELS = [ {
   maxCount: 500,
-  tickSpacing: 50
+  tickSpacing: 100,
+  minorSpacing: 10
 }, {
   maxCount: 200,
-  tickSpacing: 20
+  tickSpacing: 40,
+  minorSpacing: 8
 }, {
   maxCount: 100,
-  tickSpacing: 10
+  tickSpacing: 20, // 6
+  minorSpacing: 5
 }, {
   maxCount: 75,
-  tickSpacing: 15
+  tickSpacing: 15, // 6
+  minorSpacing: 5
 }, {
   maxCount: 50,
-  tickSpacing: 10
+  tickSpacing: 10, // 5
+  minorSpacing: 5
 }, {
   maxCount: 25,
-  tickSpacing: 5
+  tickSpacing: 5, //4
+  minorSpacing: 10000000
 } ];
 
 export default class HistogramNode extends Node {
@@ -298,7 +304,7 @@
       verticalTickLabelSet.setSpacing( tickSpacing );
       verticalTickMarkSet.setSpacing( tickSpacing );
       majorVerticalGridLines.setSpacing( tickSpacing );
-      verticalGridLines.setSpacing( ZOOM_LEVELS[ this.zoomLevelProperty.value ].tickSpacing / 5 );
+      verticalGridLines.setSpacing( ZOOM_LEVELS[ this.zoomLevelProperty.value ].minorSpacing );
       updateHistogram();
     } );
 

```

</details>

We felt it was too odd to not label the top of the chart.

**Comment by samreid** [comment]
@matthew-blackman and I started with the recommendation above, and added an adjustment for the thumbnail grid lines.  @catherinecarter can you please check the commit and the runtime behavior and let us know what you recommend?

**Comment by catherinecarter** [comment]
Looks good to me, and the thumbnails look good, too. 

Let's earmark for an interview "look-for" to see if having only a major gridline at 5 when maxCount=25 is confusing since it might be hard to tell if a stack is 1 high vs. 2 high, etc.

**Comment by samreid** [comment]
Tagging for interviews in #88, and closing. @matthew-blackman or @catherinecarter please reopen if there is more to do.

**Comment by samreid** [comment]
Oops, there is also a TODO, reopening.

**Comment by samreid** [comment]
OK, I also fixed the TODO, closing again.
