### ISSUE TITLE
Identify all fields example does not work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#261]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1060
In the examples doc, the example under "Identify All Fields" does not work it gives the error shown below in Chrome.
**Visuals**
![errorpdl](https://github.com/phetsims/projectile-data-lab/assets/41024075/f04f418a-662a-4464-86ef-902cfe7cf867)

**Comment by samreid** [comment]
@matthew-blackman indicated we could just remove the "how to list all the fields" sample code. A user can use Studio to discover the fields.

**Comment by samreid** [comment]
I removed the extraneous section, closing.
