### ISSUE TITLE
Example code may only work in studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#263]
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/1060
If you try to use the code under the "Get Projectiles for a Field" section in Studio, it seems to run as expected. In other wrappers, such as State or Simulation, you get an error.
**Visuals**
![studioonly](https://github.com/phetsims/projectile-data-lab/assets/41024075/76a3eea1-ebeb-457c-8e0d-fa7b6ec82485)

**Comment by samreid** [comment]
@matthew-blackman and I discussed this, and it is behaving as expected. The State wrapper has 2 Clients, so neither is named exactly `phetioClient`, and that wrapper is not set up to accept input like that. The standalone "Simulation" is not a wrapper at all, so there is no `phetioClient` to use in that case.  Having things work in Studio is a good stand-in for knowing they will work in a Standard or Custom PhET-iO Wrapper.  Closing.
