### ISSUE TITLE
Rounding on the Angle Stabilization slider in CODAP

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#265]
The number of decimals of the angle stabilizer value seems to be out of whack for two of the values:

<img width="193" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/d3219055-6c7e-4078-97e7-0514e5e188ba">

**Comment by samreid** [comment]
I'm seeing the same thing--rounded in the table but not in the chart labels:

<img width="1874" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/dfdcbe07-3555-4094-92e9-196dd4348ac9">

@matthew-blackman how would you like to address this?

**Comment by samreid** [comment]
<img width="1241" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/b22f242b-40f9-4447-b10c-8eda74479152">

Fixed in the commit, closing.
