### ISSUE TITLE
Hotkeys for selecting fields and Chromebook keyboard shortcuts conflict

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#266]
**Test device**
Lenovo 100e Chromebook

**Operating System**
ChomeOS 122.0.6261.118

**Problem description**
For https://github.com/phetsims/qa/issues/1060, the hotkeys used to select a particular field (`alt` + `1` - `6`) are also Chromebook shortcut keys for the icons in the dock. If I press alt + 6  on my Chromebook instead of going to field 6, a new window opened with the 6th app in my doc, which was youtube. 

The shortcut is listed here: https://support.google.com/chromebook/answer/183101?hl=en#zippy=%2Csystem-display-settings. 

Scroll down to "System and Display Settings" section. 

<img width="670" alt="Screenshot 2024-03-20 at 3 38 11 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/deb0f752-8611-420f-96d3-2361fc15ded6">

**Comment by matthew-blackman** [comment]
@terracoda do you have a recommendation for alternative hotkey patterns that won't conflict with Chrome?

**Comment by terracoda** [comment]
I think it would be a good idea to use the J-key + Number key instead of the ALT + Number. Where's the original issue that brain-stormed some options?

**Comment by matthew-blackman** [comment]
I like that idea @terracoda. Here was the issue where we started discussing this, but it may be a bit stale - https://github.com/phetsims/projectile-data-lab/issues/44

**Comment by terracoda** [comment]
And [issue #61](https://github.com/phetsims/projectile-data-lab/issues/61) discussed ideas, too.

**Comment by terracoda** [comment]
Hopefully, there won't be any conflicts with ALT + L.

ALT is a very common modifier key. In Chromebook Shft + ALT + L highlights that platform's "Launcher" button.

[Chromebook Shortcuts](https://support.google.com/chromebook/answer/183101?hl=en#name1&name2&name3&name4&name5&name6&name7)

ALT + L may be used in digital video players? 
PhET implemented ALT + L in MAL's TimingControlNode for the Step Forward button.

If you find a conflict, you might want to use F + L for fire launcher or J + L if you want to keep the first letter consistent.

**Comment by samreid** [comment]
I updated to use "J+(1-6)" and updated the keyboard help dialog. It sounds like there was no conflict with ALT+L and the J+1-6 matches the recommendations. Therefore it seems this issue can be closed.

**Comment by samreid** [comment]
@matthew-blackman requested to use F instead of J, and @terracoda and I thought this would be OK. We will do so.

**Comment by samreid** [comment]
Fixed, closing.
