### ISSUE TITLE
Needle traces disappear when setting state

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#269]
**Test device**
MacBook Air M1 chip and iPad 9th generation

**Operating System**
14.3.1 and 17.4

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1060 in the Studio and State wrappers on the first 3 screens: the launched sim won't show any previous needle marks on the speed and angle tools. 

**Steps to reproduce**
1. In the Studio wrapper, go to any screen aside from the Sampling screen. 
2. Check the Launch Angle and Launch Speed Checkboxes
3. Launch a bunch of projectiles
4. Press Test button 

**Visuals**
In Studio:
<img width="917" alt="Screenshot 2024-03-21 at 1 05 10 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/a5690905-8b2f-4d14-a67e-cda1b92fb3a5">

In Standard wrapper:
<img width="1112" alt="Screenshot 2024-03-21 at 1 05 30 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/861d1d53-b6f7-4479-a593-ae95a7cd9876">

**Comment by samreid** [comment]
Fixed and working well in my testing. @matthew-blackman can you please review/test? Please close if all is well.

**Comment by matthew-blackman** [comment]
I reviewed this with @samreid and the code is very clear and straightforward. Behavior has been tested under a variety of circumstances and everything is working well. Nice work! Closing.
