### ISSUE TITLE
No grab/release sounds for the stopwatch and measuring tape.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#270]
There are no default grab/release sounds for the stopwatch and measuring tape.  My understanding is that we're adding these to all new sims that support UI sound.   And it involves a quick conversion to RichDragListener and RichKeyboardDragListener.

The conversion for StopwatchNode can be found in the patch in https://github.com/phetsims/scenery-phet/issues/845#issuecomment-2013876745.  I have not committed it because it would seem even more odd for the measuring tape to have no grab/release sound.

**Comment by pixelzoom** [comment]
Adding sound to MeasuringTapeNode is pretty trivial, see patch in https://github.com/phetsims/scenery-phet/issues/846.

**Comment by pixelzoom** [comment]
@samreid and I discussed, and I'll proceed with adding default grab/release sounds to StopwatchNode and MeasuringTapeNode.  I'll notify @samreid and @matthew-blackman when this work is completed -- probably on Monday 3/25.

If the grab/release sounds are undesirable for this sim, then they can be turned off using the apporach shown in https://github.com/phetsims/projectile-data-lab/issues/270#issuecomment-2013896215.

If the grab/release sounds are desired for this, their output levels can be rebalanced via the `grabSoundClipOptions` and `releaseSoundClipOptions` options for RichDragListener and RichKeyboardDragListener.

**Comment by pixelzoom** [comment]
@samreid @matthew-blackman FYI, work has been completed for default grab/release sounds in StopwatchNode and MeasuringTapeNode.

**Comment by samreid** [comment]
Looks good and working well in my testing. I believe this issue can be closed.
