### ISSUE TITLE
Button text on the stopwatch icon doesn't update

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#272]
Discovered in https://github.com/phetsims/projectile-data-lab/issues/258, the "launch" text on the stopwatch icon doesn't change when the translation changes, like with ?stringTest=dynamic

**Comment by samreid** [comment]
Fixed, @matthew-blackman does that seem OK to you?

**Comment by matthew-blackman** [comment]
Looks great! Closing.
