### ISSUE TITLE
Potential Infinite Loop

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/projectile-data-lab#273]
Not blocking, but I'm unable to fuzz the normal list of sims because it pauses at PDL. Pausing execution I see:

![image](https://github.com/phetsims/projectile-data-lab/assets/480878/f39e5ad0-092e-4294-86ee-b87162b2e952)

**Comment by samreid** [comment]
Thanks @jonathanolson, we reproduced the problem and will address it in https://github.com/phetsims/projectile-data-lab/issues/274, closing.
