### ISSUE TITLE
Interval Tool doesn't return to default position with Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#278]
**Test device**
MacBook Air M1 chip + iPad

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
Seen while verifying https://github.com/phetsims/projectile-data-lab/issues/267: 
The Interval Tool will appear on the left side of the field after Reset all. Then it isn't possible to move the tool all the way to the right side. 

This issue wasn't present in 1.0.0-dev.22.

**Steps to reproduce**
1. On the Measure Screen select the Interval Tool
2. Move the tool all the way to the right
3. Press Reset All
4. Select the Interval tool (appears on the left side instead of the center)
5. Try to move the tool all the way to the right

**Visuals**

https://github.com/phetsims/projectile-data-lab/assets/87318828/94994b89-cd30-4318-b6ce-3746b192e2e2

**Comment by samreid** [comment]
On hold pending work in #280

**Comment by samreid** [comment]
Fixed in the commits, @Nancy-Salpepi can you please verify/test in main, and close if all is well?

**Comment by Nancy-Salpepi** [comment]
Looks good in main! Closing.
