### ISSUE TITLE
Add position labels to interval tool handles while dragging

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#279]
Kelly F. and @catherinecarter mentioned that it would be nice to have position labels for the interval tool handles while dragging them. Let's implement this as a quality-of-life improvement for the interval tool. The labels do not need to be stateful or instrumented.

**Comment by catherinecarter** [comment]
I love it! There are a couple layout issues that will need to be addressed. Not sure how, but here's what I found:
- the left edge and the "no air resistance" overlap (1st image)
- the mean readout gets lost when the handles are close together (2nd image)

<img width="245" alt="Screenshot 2024-04-02 at 11 46 37 AM" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/6379a945-bb1a-461f-935e-781f2952901c">
<img width="245" alt="Screenshot 2024-04-02 at 11 47 51 AM" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/0e13baab-7df9-4f7e-a517-d18238ac7b43">

**Comment by matthew-blackman** [comment]
Thanks @catherinecarter! Should be fixed now. Feel free to close if all looks good.

**Comment by catherinecarter** [comment]
Looks great. Nice work.
