### ISSUE TITLE
Launcher animation code, bring to production quality now that we know we like it

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#28]
Switching fields and configurations not fully implemented
For launcher animation: SR and MB would like to explore how it could be implemented in the step function, rather than using Animation.

**Comment by samreid** [comment]
In the commit, I removed unnecessary Property instances. This may help with #24 as well. I also converted from undefined to null. I'm not convinced we need to abandon `Animation`, it seems clear and simple, and seems to be working well. It doesn't need to be phet-io intrumented as far as I can tell. @matthew-blackman can you please review my change and advise.

**Comment by matthew-blackman** [comment]
Labeling for collaboration since this overlaps with #51 and there is an important TODO in LauncherNode.

**Comment by matthew-blackman** [comment]
@samreid and I agree that the recent updates to the launcher rotation code have brought it up to production quality. We cleaned up a remaining TODO in the above commit. Closing.
