### ISSUE TITLE
"Configuration" radiogroup. Is there a better name?

### ISSUE THREAD

**Issue by terracoda** [phetsims/projectile-data-lab#281]
This question was asked in https://github.com/phetsims/projectile-data-lab/issues/107, and has been tossed around, but not sure if it just fell off the radar.

Opening a single issue here to ask again, if there is a better name for the "Configuration" radiogroup.
- Launcher Configuration
maybe?

Screen 1
![Screenshot 2024-04-19 at 08 12 55](https://github.com/phetsims/projectile-data-lab/assets/1902116/abe4d03a-d380-4cf9-9a80-f61dbf7b1606)

Screen 2
![Screenshot 2024-04-19 at 08 20 35](https://github.com/phetsims/projectile-data-lab/assets/1902116/24088f81-1e4f-4ec0-bab6-8afe67089207)

Screen 3
![Screenshot 2024-04-19 at 08 19 55](https://github.com/phetsims/projectile-data-lab/assets/1902116/a9545ee8-b4aa-4790-b4e9-a9859db578c4)
![Screenshot 2024-04-19 at 08 13 21](https://github.com/phetsims/projectile-data-lab/assets/1902116/e6dc3223-cb72-429a-a883-1a3a15c462fa)

Screen 4
![Screenshot 2024-04-19 at 08 13 40](https://github.com/phetsims/projectile-data-lab/assets/1902116/cd5cf794-a168-490d-8d19-2f79e906e667)

**Comment by pixelzoom** [comment]
Is this issue referring to the the tandem name, or something else?  Whatever name this refers to, it should ideally be consistent with the tandem name for the group.

**Comment by matthew-blackman** [comment]
@pixelzoom this issue is for potentially renaming the 'Configuration' heading on the top launch panel section. If we decide to change the heading we will make sure to update all tandems for consistency.

**Comment by terracoda** [comment]
Maybe the entire box needs a heading (visual label)

Configure Launcher or Launcher Configurations
- Set Angle (and Height) ??
- Choose Projectile
- Choose Launcher
   - Mystery
   - Custom
- Customize Launcher
- Choose/Set Sample Size

Using verbs can encourage interaction, and differentiates, the "Launch Angle" checkbox from the Launcher Angle radio buttons.

**Comment by terracoda** [comment]
The root of the issue is creating simple group names, but also have a little mix with actual button names as one of the screens has radio buttons with on-screen labels.

**Comment by matthew-blackman** [comment]
On 4/19, @terracoda, @catherinecarter and I agreed that 'Orientation' is a better term than 'Configuration' to capture the right degree of specificity for the launcher's mean angle and height. We agreed that 'Configuration' is too broad a term, and that the entire launch panel could be considered part of the launcher 'configuration'. 'Orientation' suggest changing the spatial layout and positioning of the launcher, which works well. Let's continue in https://github.com/phetsims/projectile-data-lab/issues/303. Closing.
