### ISSUE TITLE
Should I hear radiobutton sound when selecting field using hotkeys?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#284]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1068, on the first 3 screens I don't hear any sound when I switch fields using the hot keys. Should I hear the radio button sound here? It seems oddly quiet.

**Comment by matthew-blackman** [comment]
Good idea! This has been added in the commit. Feel free to close if it sounds okay to you.

**Comment by Nancy-Salpepi** [comment]
Sounds great! Since this is an RC, keeping open for verification in next RC.

**Comment by Nancy-Salpepi** [comment]
@matthew-blackman what are your thoughts on hearing a sound when I jump to the first/last projectile on the Field Sign using `home` and `end` keys?

**Comment by matthew-blackman** [comment]
@Nancy-Salpepi also oddly quiet. Can you open an issue?

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.2
