### ISSUE TITLE
Distance and Launch Angle values overlap with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#286]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1068, on the first 3 screens when the measuring tape is in the default position, the distance value may occlude Launch Angle value. This is seen with ?stringTest=dynamic. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to url
2. Go to any of the first 3 screens, and check Measuring Tape and Launch Angle checkboxes
3. Press the right arrow key a couple of times

**Visuals**

https://github.com/phetsims/projectile-data-lab/assets/87318828/41bc7747-16bf-4654-88da-79723cd1ff3e

**Comment by Nancy-Salpepi** [comment]
also overlap when the launch angle is zero (although I'm not sure what can be done about any of these instances):
<img width="282" alt="Screenshot 2024-04-10 at 3 56 13 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/85ac2c07-438e-4e21-a56a-7a1897fc928a">

**Comment by samreid** [comment]
In discussion with @matthew-blackman, perhaps the readout could be above the measuring tape? That won't overlap other things and won't be occluded by a finger on mobile.

**Comment by samreid** [comment]
I addressed the recommendations above.

@matthew-blackman can you please review/test?

<img width="224" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/94548f63-d339-4b8c-854f-617d9e756099">

<img width="157" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/1b878d04-f5aa-44bd-96ba-40d2dba01a7b">

<img width="266" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/dbf7379b-526e-425d-91ad-ff86b2adf594">

**Comment by matthew-blackman** [comment]
The updated layout and positioning looks good. Nice work @samreid! The distance text works well above the tape measure. I reviewed the commits and all are very straightforward. Marking as ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Only minor note is that the tape itself can cover important speed info when launching from a zero angle. If this is alright, it can be closed.
![minornote](https://github.com/phetsims/projectile-data-lab/assets/41024075/2b6b18af-9fff-4c6c-a5f8-69e4fdd936f3)

**Comment by samreid** [comment]
@matthew-blackman and I discussed it and agreed it is OK. Closing.
