### ISSUE TITLE
Add phetioFeatured: true

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#29]

**Comment by samreid** [comment]
I added some `phetioFeatured: true` for things that seem to warrant it, like the `fieldProperty` and radio buttons, and major UI components. VisibleProperties that are wired up to checkboxes.  I omitted it for panels, and panel sections.  Would be good to review together and make progress. But we may need to consult with @arouinfar soon as well, like for #30

**Comment by samreid** [comment]
<details>

```diff

Subject: [PATCH] Eliminate buggy listener that completed a sample when changing selected sample, see https://github.com/phetsims/projectile-data-lab/issues/103
---
Index: js/TreeNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/TreeNode.ts b/js/TreeNode.ts
--- a/js/TreeNode.ts	(revision 96d7e6c016acd0768c6151bd182d5320f21d6db4)
+++ b/js/TreeNode.ts	(date 1706650948330)
@@ -14,6 +14,7 @@
 import PhetioElement from './PhetioElement.js';
 import optionize from '../../phet-core/js/optionize.js';
 import { PhetioID } from '../../tandem/js/TandemConstants.js';
+import StudioQueryParameters from './StudioQueryParameters.js';
 
 const PhetioIDUtils = window.phetio.PhetioIDUtils;
 
@@ -264,7 +265,10 @@
     const p = document.createElement( 'p' );
     p.classList.add( 'treeElement' );
 
-    if ( this.isLinkedElement ) {
+    if ( StudioQueryParameters.highlightFeaturedElements && this.phetioElement?.metadata.phetioFeatured ) {
+      p.classList.add( 'featured' );
+    }
+    else if ( this.isLinkedElement ) {
       p.classList.add( 'linkedElement' );
     }
 
Index: studio.css
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/studio.css b/studio.css
--- a/studio.css	(revision 96d7e6c016acd0768c6151bd182d5320f21d6db4)
+++ b/studio.css	(date 1706650621548)
@@ -269,6 +269,10 @@
   color: blue; /*TODO: match this styling with the linked div panel?  Or generally improve it?*/
 }
 
+.featured {
+  color: green;
+}
+
 .linkedDivDescriptor {
   font-size: 1.3em;
   margin-bottom: 12px;
Index: js/StudioQueryParameters.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/StudioQueryParameters.ts b/js/StudioQueryParameters.ts
--- a/js/StudioQueryParameters.ts	(revision 96d7e6c016acd0768c6151bd182d5320f21d6db4)
+++ b/js/StudioQueryParameters.ts	(date 1706650926068)
@@ -40,6 +40,11 @@
     // Used to wire up communication to a parent frame for getting the standard PhET-iO wrapper
     exposeStandardPhetioWrapper: {
       type: 'flag'
+    },
+
+    // Internal use only for design
+    highlightFeaturedElements: {
+      type: 'flag'
     }
   } );

**Comment by samreid** [comment]
@zepumph said the patch above seems reasonable. He wondered if we would want to keep the "linked element" highlighting with it.

**Comment by samreid** [comment]
It looks like this:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/b436cee3-30ae-4996-9548-2f2821c168d7)

**Comment by zepumph** [comment]
To me it is awkward that the CSS has to negate the linked element CSS. Perhaps we could make it bold or underlined or a bigger font size, so that the blue linked elements were still shown. Or somehow make it so that featured linked elements were a second color.

**Comment by samreid** [comment]
Thanks, I went with opacity as a way to distinguish between featured and non-featured, and this preserves coloring of linked elements.

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/d6bd5212-38bd-4705-98ca-64ba68e7c800)

**Comment by matthew-blackman** [comment]
This is related to work being done in https://github.com/phetsims/studio/issues/288

**Comment by arouinfar** [comment]
In general, @matthew-blackman and I have been discussing what to feature in #30, but once that wraps up we should do another pass-through to make sure we didn't miss anything. In particular, I don't think we discussed what to feature under `model.fields`.

**Comment by arouinfar** [comment]
Now that #30 has wrapped up, I'd like to take another look through the tree to see if anything else that should be featured.

**Comment by samreid** [comment]
Thanks! We appreciate it. Also, we were wondering if the radio buttons (not the groups) should also be featured? We noticed many (all?) are not currently featured.

**Comment by arouinfar** [comment]
> Also, we were wondering if the radio buttons (not the groups) should also be featured? We noticed many (all?) are not currently featured.

We feature many common code components (like RadioButtonGroup and Checkbox) so that their linked properties show up correctly in the Featured tree. However, individual radio buttons do not have linked properties as children, so I don't see any reason to feature them. Their `enabledProperty` and `visibleProperty` are featured by default, so the radio buttons will show up in the featured tree.

**Comment by arouinfar** [comment]
I've completed my review, and identified a few additional elements to feature. For brevity, I only specified things once, but if an element appears on multiple screens, it should be featured on all of them.

```ts
/* eslint-disable */
window.phet.preloads.phetio.phetioElementsOverrides =
  {
    "projectileDataLab.measuresScreen.view.histogramAccordionBox.histogramNode.valuesChartOverlay.showValuesChartOverlayProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.samplingScreen.view.histogramAccordionBox.thumbnailContainerNode.sample40ThumbnailNode.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.samplingScreen.view.histogramAccordionBox.thumbnailContainerNode.sampleSize15ThumbnailNode.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.samplingScreen.view.histogramAccordionBox.thumbnailContainerNode.sampleSize2ThumbnailNode.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.samplingScreen.view.histogramAccordionBox.thumbnailContainerNode.sampleSize5ThumbnailNode.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.samplingScreen.view.histogramAccordionBox.thumbnailContainerNode.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.sourcesScreen.view.launchPanel.customLauncherSection.angleStabilizerSection.visibleProperty": {
      "phetioFeatured": true
    },
    "projectileDataLab.variabilityScreen.view.histogramAccordionBox.histogramNode.binControlNode.visibleProperty": {
      "phetioFeatured": true
    }
  };
  ```
  Note that these are just suggestions, so feel free to veto if you disagree @matthew-blackman @samreid. Also happy to chat if you want any clarification.

**Comment by samreid** [comment]
I implemented the recommendations above and tested in Studio. It was straightforward and the results look good. I recommend closing this issue.
