### ISSUE TITLE
Consider using new `ResetAllButton.isResettingAllProperty`

### ISSUE THREAD

**Issue by jbphet** [phetsims/projectile-data-lab#290]
In https://github.com/phetsims/tambo/issues/190 I added a static `isResettingAllProperty` flag to `ResetAllButton`.  In subsequently looking through the codebase for opportunities to use it, I found the file `isResettingAllProperty.ts` in projectile-data-lab.  I though y'all might want to know that there is now a common code version of this that might be a suitable replacement.

**Comment by samreid** [comment]
Fixed and working well in my testing. @matthew-blackman do you mind double checking? If it seems good, please label for cherry-picking and we can request QA testing in main or RC.2.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
I had a fairly bad instance of freezing with multitouch. I saw it on iPad, and don't have a touch screen on my computer, so I don't have a console readout.

Steps:
1. Go to the third screen and turn on the interval tools.
2. Drag around one of the ends of the tool,
3. While dragging, press reset all, make sure the dragging finger is moving at this point
4. With that finger still down, turn on interval tools again
5. Drag the down finger over the tool to snag it and drag it. It should catch the "middle" of the tool
6. Press reset all again.


https://github.com/phetsims/projectile-data-lab/assets/41024075/c4df07dd-004b-4e13-8338-bdabc96698d4

**Comment by matthew-blackman** [comment]
Continuing multitouch behavior in https://github.com/phetsims/projectile-data-lab/issues/321. This issue can be closed.
