### ISSUE TITLE
Add sound when auto-generating data using hotkeys

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#293]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1068, with Auto-Generate Data on, there is no sound when I use the launch shortcut `option` + `L`. 

**Steps to reproduce**
1. In preferences, turn on Auto-Generate Data
2. On any screen, press `option` + `L`

**Comment by matthew-blackman** [comment]
Nice work! This is ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.2
