### ISSUE TITLE
Possible to select a field using hotkeys when radio button is disabled/not visible

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#294]
**Test device**
MacBook Air M1 chip
:
**Operating System**
14.4.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1068, in Studio on the first 3 screens:
It is still possible to access a field using the hotkeys after making that field's radio button disabled or invisible.

**Steps to reproduce**
Here is an example:
1. In studio, make `projectileDataLab.measuresScreen.view.fieldRadioButtonGroup.field5RadioButton.visibleProperty` false
2. Press the Test button
3. Press F + 5
OR
1. Make `projectileDataLab.measuresScreen.view.fieldRadioButtonGroup.field5RadioButton.enabledProperty` false
2. Press the Test button
3. Press F + 5

**Visuals**
<img width="1099" alt="Screenshot 2024-04-15 at 1 08 38 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/25265fae-7acf-413c-a30a-7ef55dc5520c">
<img width="1099" alt="Screenshot 2024-04-15 at 1 11 49 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/1a19a5ba-c1a3-4c64-b9d8-167f68deb95e">

**Comment by Nancy-Salpepi** [comment]
This is working nicely in main.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks ok in rc.2
