### ISSUE TITLE
Sample appears when stopping continuous sampling

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#295]
To trigger this behavior:

1. Start continuous sampling
2. Pause the sim
3. Press the clear button
4. Press the button to stop continuous sampling (while still paused)

The sim's current behavior is that it will erroneously create a sample on step 4. This sample should not appear. All other behavior should stay the same. Let's fix it!

**Comment by matthew-blackman** [comment]
This is fixed in the commit. @KatieWoe and @Nancy-Salpepi please confirm. @samreid and I also wanted to bring attention here for further testing, as we feel that additional edge cases in this area are likely.

**Comment by Nancy-Salpepi** [comment]
Looks good to me too.

**Comment by KatieWoe** [comment]
Looks good in rc.2
