### ISSUE TITLE
Keyboard nav may activate without pressing tab

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#296]
**Test device**
Chromebook
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1068
I have found situations where you can activate keyboard nav without pressing tab. The first is, if you press they arrow keys after having interacted with the field box with the mouse, the second is if you use the arrows after interacting opening the Bin Width/number dropdown with the mouse.

**Visuals**
<img width="202" alt="thing2" src="https://github.com/phetsims/projectile-data-lab/assets/41024075/bee1998b-c0f4-4325-85e7-3467d90caa5e">
![Screenshot 2024-04-17 112654](https://github.com/phetsims/projectile-data-lab/assets/41024075/182c7a83-25e2-4b20-a8bc-8ab0824da4ee)

**Comment by samreid** [comment]
@jessegreenberg said:

> That makes sense. This is still the expected behavior at this time though. We need focus to be placed in the sim for accessibility, and using the arrow keys should resume from where focus is. This is related to https://github.com/phetsims/joist/issues/750, if that is done the mouse+keyboard interaction may feel more consistent.

**Comment by matthew-blackman** [comment]
Closing based on the discussion above.

**Comment by terracoda** [comment]
Also, just adding this comment, so QA is aware... Alt Input is always "active", i.e., enabled. It is not ever disabled in a sim that has the feature.
