### ISSUE TITLE
Should eraser clear the timer?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#297]
**Test device**
ChromeBook
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1068
When you press the eraser button the timer does not reset, even though the projectile it measured is gone. This may need a second look.

**Comment by matthew-blackman** [comment]
Reviewed this with @samreid and all looks good. Labeling ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Seems fixed. I did notice that this may be complicated by switching fields. As it is, the timer is not affected by switching fields, so if you start it and switch fields, it is still active, and if you erase the new field the time is reset, even thought the ball it was originally measuring still exists in the first field. At this point this is so minor and I'm not sure another behavior would actually be preferable. But I wanted to check before closing.

**Comment by Nancy-Salpepi** [comment]
I noticed the same behavior @KatieWoe reported in https://github.com/phetsims/projectile-data-lab/issues/297#issuecomment-2080151027 while I was testing over the weekend.

**Comment by matthew-blackman** [comment]
Great find @KatieWoe and @Nancy-Salpepi! Continuing over in #320. Can this issue be closed?

**Comment by KatieWoe** [comment]
Sure!
