### ISSUE TITLE
Uncentered "no air resistance"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#298]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1068
If you use dynamic locale, the "no air resistance" string is not centered on the 4th screen
**Steps to reproduce**
1. Use `?stringTest=dynamic`
2. Go to the 4th screen
3. Press the left arrow twice to make strings shorter

**Visuals**
<img width="131" alt="nocenter" src="https://github.com/phetsims/projectile-data-lab/assets/41024075/2daae21a-d808-4848-9884-99b97f3ae3a9">
Vs on other screens:
<img width="136" alt="center" src="https://github.com/phetsims/projectile-data-lab/assets/41024075/facc3374-e393-4052-8129-fb5cb07349e7">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: Projec
URL: https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.0-rc.1/phet/projectile-data-lab_all_phet.html?stringTest=dynamic
Version: 1.0.0-rc.1 2024-04-09 18:41:49 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language: en-US
Window: 1280x631
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
Reviewed this with @samreid and all looks good. Labeling ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.2
