### ISSUE TITLE
Publishing a standalone sim for Sampling screen

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#299]
The design team has discussed in the past that we would also like to publish the Sampling screen separately as its own standalone sim. Let's discuss how this will look in implementation before publishing PDL, to avoid making additional work.

**Comment by samreid** [comment]
To decide:

- [ ] repository name
- [ ] simulation name
- [ ] screen name
- [ ] we are aware of at least 2 preferences that will need to be removed. Anything else?
- [ ] any changes in functionality
- [ ] any changes in the PhET-iO studio tree?
- [ ] publication timeline?
- [ ] Should we use the same SHAs as RC.2 for Projectile Data Lab to minimize QA requirements?

In particular, if there are any changes that would affect Projectile Data Lab or its PhET-iO API, we would like to implement that before publishing 1.0.

**Comment by matthew-blackman** [comment]
From design meeting discussion 4/18

- Simulation name: Projectile Sampling Distributions
- Repository name: projectile-sampling-distributions
- Screen name (only for PhET-IO): Sampling
- Remove preferences for 'Projectile type affects speed' and 'Show standard error'
  - MB and SR will check in with CM and MK about preferences pattern for 1-screen standalone build
- KF and CC would like to discuss ways to narrow down the horizontal range of the histogram, so that the data appears larger.

**Comment by matthew-blackman** [comment]
Everything in this issue has been addressed. Nice work! Closing.
