### ISSUE TITLE
Refine the studio tree

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#30]
@matthew-blackman and I would like to review the tree. @pixelzoom also recommends looking at the design section of https://github.com/phetsims/phet-io/issues/1969#issuecomment-1753353643

We would also like to check in with @arouinfar once this is ready.  @pixelzoom recommends this may be better sooner rather than later.

**Comment by matthew-blackman** [comment]
Note about the Stopwatch: If we decide to go with a draggable design for the stopwatch in #94, we may want to implement a more traditional StopwatchNode which requires a Stopwatch instance. Otherwise, the Stopwatch in the VSMModel can be removed.

**Comment by samreid** [comment]
@matthew-blackman and I completed our review and refinement for VSM. We still need to do Sampling.

**Comment by matthew-blackman** [comment]
Notes from 1/26 meeting (MB, AR, SR)
- In examples.md, explain how to get range of available landed projectiles to select
- SelectedProjectileNumberProjectileNumber should be an integer - min at zero instead of -infinity
- NumberOfCompletedSamples is instrumented on Sampling. Should we do this for numberOfLandedProjectiles
- We do not see a problem with the each model's launcherProperty not being stateful, since the currently visible launcher is still accessible with two lines of code
- On screens 1-3, model-levels launcher properties should be consistent in access (either all readonly or all read-write)
- It is not necessary to be able to change the currently visible launcher through model-level properties in studio. The user can read them, and can use the UI of the sim to do this. They can also set them for each field with the API.
- MeasuresScreen.model.launcherProperty does not need to enumerate all possible launchers in its validValues
- examples.md should be the minimum possible set of necessary things to describe how to customize the sim.
- Dynamic property for ProjectileType should be instrumented at model level
- isContinuousLaunchingProperty should not be featured since it feels like an implementation detail

**Comment by matthew-blackman** [comment]
@samreid and I implemented the changes in the checklist above, except for 'isContinuousLaunchingProperty should not be featured since it feels like an implementation detail'. We feel that isContinuousLaunchingProperty should be featured, since it is a central property to the behavior of the sim, and a designer could use it to preload a sim with launching projectiles. @arouinfar does that sound okay to you?

**Comment by matthew-blackman** [comment]
Remaining work on dev first pass:
- Sampling view

**Comment by matthew-blackman** [comment]
Notes from 1/31 discussion with @arouinfar:
- isContinuousLaunchingProperty should be stateful and unfeatured
- Global model properties should be featured
- Feature launcherProperty
- Unfeature emitters
- Stopwatch properties should not be at the field level
- For measuring tools, unfeature implementation details and feature the core measurement value (may already be taken care of in common code)
- Hiding the launch button in the stopwatch should collapse the size dynamically (pending design approval of component)
- Histogram expandedProperty should be featured

We are up to the Variability screen view - histogramAccordionBox component in our review.

**Comment by samreid** [comment]
OK I addressed 5 requests. Moved 2 to side issues. 2 remaining checkboxes require consultation.

**Comment by matthew-blackman** [comment]
Notes from 2/2 discussion with @arouinfar:

- [ ] histogramNode visibleProperty should be readonly
- [ ] binWidthLabel visibleProperty uninstrumented
- [ ] zoomLevelProperty should be instrumented for histogram
- [ ] zoomLevelProperty should be linked to zoomButtonGroup
- [ ] All panel visibleProperties should be featured
- [ ] Section visibleProperties should be featured
- [ ] For all panel sections that only have a single radio button group, uninstrument the visibleProperty of that radioButtonGroup
- [ ] projectileSelectorNode visibleProperty should be featured
- [ ] projectileSelectorNode increment/decrement buttons should have instrumented visibleProperty
- [ ] projectileSelectorNode enabledProperty should be unfeatured
- [ ] stopwatchLaunchButton should be nested under the stopwatchNode
- [ ] customLauncherSection visibleProperty should be featured
- [ ] angleStabilizer slider should have an enabledProperty

We are up to the Measures screen model

**Comment by arouinfar** [comment]
I reviewed the Measures Screen tree, focusing on elements that are new to this screen.

- [ ] `launchPanel.launcherSection` does not resize appropriately for dynamic layout, specifically on the Measures screen. Here are a few examples:
    <img src="https://github.com/phetsims/projectile-data-lab/assets/8419308/af90cbd0-2332-4d84-a493-c1780895f41e" width=200> <img src="https://github.com/phetsims/projectile-data-lab/assets/8419308/393c026b-5693-4c43-b209-29c109f65d8a" width=200> <img src="https://github.com/phetsims/projectile-data-lab/assets/8419308/41547b39-cc85-47fa-abe0-9a239a8363f0" width=200>
- [ ] `model.intervalTool` and `view.intervalToolNode` need to be featured for linked properties to appear in the Featured tree.
- [ ] Feature `dataMeasures*Overlay.visibleProperty`

I also have a few questions to discuss with @matthew-blackman related to the Interval Tool to discuss when we meet on Monday, but overall this screen was in great shape!

**Comment by arouinfar** [comment]
>  When I implemented "projectileSelectorNode increment/decrement buttons should have instrumented visibleProperty", I saw that it was featured by default. Is that as desired?

Thanks for checking @samreid. Yes, that is the desired behavior. In PDL, clients may want to prevent scrolling through the projectile history and always display the latest projectile info. In general, increment/decrement buttons are often associated with a display so we feature the `visibleProperty` so clients can easily turn the component into a non-interactive readout.

**Comment by matthew-blackman** [comment]
Meeting notes 2/5 (AR, SR, MB)

- [ ] Rename isLauncherCustonRadioButtonGroup to mysteryOrCustomRadioButtonGroup
- [ ] Feature the following properties on the field level - meanDistance, mysterLauncher, mysteryOrCustom, standardDeviationDistance, standardError, customLauncher
- [ ] Instrument intervalTool inputEnabledProperty
- [ ] In examples.md, document how to access the range of the interval tool

**Comment by samreid** [comment]
All ideas implemented or moved to side issues. @arouinfar said she would like to phetioFeatured in the context of #29.  Nice work @matthew-blackman @arouinfar and myself.  Closing.

**Comment by matthew-blackman** [comment]
Reopening with feedback from 4/5 meeting with @arouinfar:
- Interval tool model properties should be featured.
- Instrument the simPreferences UI
- Create an 'audioPreferences' tandem for all audio preferences.

**Comment by matthew-blackman** [comment]
Ready for your review @arouinfar. It looks like the sim preferences and audio preferences UI are already instrumented under `projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels`. Can you confirm?

**Comment by arouinfar** [comment]
Looks good on main, thanks @matthew-blackman.

> It looks like the sim preferences and audio preferences UI are already instrumented under `projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesPanels`. Can you confirm?

Yes, looks like it's all there. Not sure why things appeared to be missing during our review together!
![image](https://github.com/phetsims/projectile-data-lab/assets/8419308/20b43b47-c084-4bc5-aba4-e01e23541933)

**Comment by pixelzoom** [comment]
Reopening.  The API was not regenerated.  And this change looks odd to me.  Why is there an additional `audioPreferences` tandem inserted here? 

<img width="668" alt="screenshot_3194" src="https://github.com/phetsims/projectile-data-lab/assets/3046552/56117545-5603-42f1-9d7d-755f9d5b6aab">

**Comment by samreid** [comment]
From slack:

```

Chris Malley
  1 hour ago
After a pull-all, git-hooks are failing with:
projectile-data-lab BREAKING PROBLEMS
PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl
PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.playLandingSoundControl
projectile-data-lab DESIGN PROBLEMS
PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl
PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.playLandingSoundControl
New PhET-iO Element not in reference: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.audioPreferences
projectileDataLab.measuresScreen.model.intervalTool.edge1Property.phetioFeatured changed from "false" to "true"
projectileDataLab.measuresScreen.model.intervalTool.edge2Property.phetioFeatured changed from "false" to "true"
10 replies


Chris Malley
  1 hour ago
grunt generate-phet-io-api shows this rather odd addition to audioPreferencesPanel. Is this what you intended to do? 
@Matt Blackman
 
@samreid
screenshot_3194.png
 
screenshot_3194.png




Sam Reid
  1 hour ago
Yes, we matched that with something else and checked with 
@arouinfar
, if I recall correctly. I’ll double check and commit


Chris Malley
  1 hour ago
I pushed an updated projectile-data-lab-phet-io-api.json, so that I can continue working.
:+1:
1



Chris Malley
  1 hour ago
audioPreferencesPanel.audioPreferences  smells like a workaround for not being about to get audioPreferencesPanel to add sim-specific audio controls.


Chris Malley
  1 hour ago
When common controls like the “Audio Features” toggle are someday instrumented, will they be under `audioPreferencesPanel.audioPreferences . I think not.  And it’s not even possible because you’re creating that tandem in the sim. (edited) 


Amy Rouinfar
  1 hour ago
The structure mirrors sim preferences which are collected under simulationPreferencesPanel.simPreferences.


Chris Malley
  43 minutes ago
simulationPreferencesPanel is sim specific.  audioPreferencesPanel is not. How are controls that are common to all Audio panels going to be instrumented someday?  And if this is the convention for the Audio preferences panel, why is audioPreferencesPanel.audioPreferences created in the sim instead of joist?


Sam Reid
  41 minutes ago
I’ll be in a meeting for a bit, let me and 
@Matt Blackman
 know what you recommend.


Chris Malley
  39 minutes ago
It seems like this additional level that’s being added to *PreferencesPanel is a workaround for not having the panel’s tandem name — a joist deficiency.  For panels in general, we would never do particlesPanel.particleControls.numberOfParticlesSpinner , we would do particlesPanel.numberOfParticlesSpinner .  Why are we adding an intermediate tandem for Preferences panels?


Chris Malley
  38 minutes ago
This could be solved by adding:
SimulationPreferencesPanel.TANDEM_NAME
AudioPreferencesPanel.TANDEM_NAME
etc.
```

**Comment by matthew-blackman** [comment]
@samreid and I discussed this with @pixelzoom and we are all in agreement that the 'simPreferences' and 'audioPreferences' tandems do not appear to be needed. We removed these tandem levels in the commit, and would like to open a common code issues to remove the 'simPreferences' tandem for the children of SimulationPreferencesContentNode.

Nice work! This issue can be closed.
