### ISSUE TITLE
Change 'Configuration' to 'Orientation'

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#303]
From https://github.com/phetsims/projectile-data-lab/issues/281, we'd like to change the term 'Configuration' to 'Orientation' Let's do it!

**Comment by matthew-blackman** [comment]
Note: The model.md (and possibly other documentation files) will need to be updated as well.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.2
