### ISSUE TITLE
Projectile Sampling Distributions: Custom histogram zoom levels for PSD sim

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#310]
From Slack, @catherinecarter said:

> Since we don’t have the other screens, we don’t need the y-axis to zoom all the way to 500, and I found myself wanting a step between 200 and 500. With this being the only screen, can we change the zoom levels to be a max on the y-axis in increments of 25 and range from 25 to 225 or 250?

This sounds like a great idea. Let's customize the zoom levels for the PSD histogram.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good
