### ISSUE TITLE
CODAP Wrapper: Add docked variables for screenIdentifier and sampleSize

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#313]
Let's add variables to the CODAP wrapper for screenIdentifier and sampleSize. SampleSize is technically available in the 'Field' variable for the Sampling screen, but @catherinecarter and I discussed that it may not be obvious to users that the sample number is part of the field identifier string. We would like to allow for multiple ways for users to differentiate the sample means and individual projectile data, so it makes sense to also have a 'Sample Size' variable (numeric).

**Comment by samreid** [comment]
For the sampling screen, we will parse the field ID to get the sample size.
a) For the other screens, the sample size will be the same as the total number of landed projectiles at that moment. But that "at that moment" part means it will become inconsistent when another projectile lands. Therefore we choose to go with (b):
b) For the other screens, the sample size will be blank
We need a checkbox, and a query parameter.

**Comment by samreid** [comment]
Code looks good. Runtime looks good:

<img width="2294" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/c2327d0d-5296-43df-a332-46d9a1911ef6">

I also tested with projectileDataWrapper.html?sim=projectile-data-lab%26screens=2,4%26sampleSize=false and it behaved as expected. This looks ready to close. @matthew-blackman anything else before closing?

**Comment by matthew-blackman** [comment]
Great! Let's continue the offshoot work in https://github.com/phetsims/projectile-data-lab/issues/333. Closing.
