### ISSUE TITLE
Screen identifiers should not include the word 'screen'

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#314]
Discussing this with @catherinecarter, we agreed that makes the identifiers too long. Let's use `'variability', 'sources', 'measures', 'sampling'` instead of `'variabilityScreen', 'sourcesScreen', 'measuresScreen', 'samplingScreen'`.

**Comment by matthew-blackman** [comment]
This has been implemented in the commit. Marking to cherry-pick.

**Comment by matthew-blackman** [comment]
The above commit uses the screen identifier values instead of tandem names, as well as adds support for the the screen identifier variable to the CODAP wrapper. Marking ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Unless I'm misunderstanding this issue, this doesn't seem to have occurred
![notthecase](https://github.com/phetsims/projectile-data-lab/assets/41024075/5b455763-4941-43ca-b46f-6972c9a878c5)

**Comment by catherinecarter** [comment]
@KatieWoe - I believe this issue is referring to what string will be passed into CODAP as the title of a column heading. I don't believe this is meant to refer to the PhET-iO ID in studio.

**Comment by KatieWoe** [comment]
In that case, what should I check in rc.2?

**Comment by KatieWoe** [comment]
We haven't been given anything to do with codap in these tests. I was told that would be next release. I don't know how to check this table.

**Comment by catherinecarter** [comment]
Gotcha. We will await instructions from @matthew-blackman and @samreid and I'll take a look in the meantime. Thanks, Katie!

**Comment by KatieWoe** [comment]
Discussed on zoom. This was checked by examining the state using code from the examples doc. Things look ok, closing.
