### ISSUE TITLE
Projectile Sampling Distributions: Remove bin width of 10

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#317]
Discussing this with @catherinecarter and Kelly, we agreed that the bin width of 10 is not useful in the PSD sim. The means are less spread out than the raw data, so the bin widths of 10 is not necessary. Let's remove this option from PSD.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good
