### ISSUE TITLE
Projectile Sampling Distributions: 'Number of bins' is ambiguous with updated histogram range

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#318]
Now that the PSD histogram range is from 20-80 instead of 0-100, the bin strategy 'Number of bins' is now ambiguous. Since it's not clear whether it applies to the field or the histogram, @catherinecarter and Kelly F agreed that the 'Bin strategy' preference can be removed from the PSD sim.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good
