### ISSUE TITLE
Should the histogram sound button be disabled when sound is off?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#319]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari 17.4.1

**Problem description**
For https://github.com/phetsims/qa/issues/1079, I noticed that the histogram sound button is still enabled when the sound is off. 
I looked at Number Compare and Number Play and the Sound button (megaphone) is disabled when the sound is off. 

**Steps to reproduce**
1. On any screen launch some projectiles
2. Turn off the sound in the nav bar

**Visuals**

Here is what Number Play looks like:

https://github.com/phetsims/projectile-data-lab/assets/87318828/279602bb-1d04-4ef2-81d4-a32f26ab0092

**Comment by Nancy-Salpepi** [comment]
Looks good on main in both sims!

**Comment by KatieWoe** [comment]
Looks good in both
