### ISSUE TITLE
Reset the stopwatch when switching fields

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#320]
In https://github.com/phetsims/projectile-data-lab/issues/297, it was discovered that it doesn't make sense to keep the stopwatch running when switching fields. The timed projectile is no longer visible, so the timer doesn't apply. We don't want to introduce a field-specific timer state for the sake of simplicity. Let's clear and pause the stopwatch when switching fields to save the user a click.

**Comment by samreid** [comment]
Cherry picked in both sims.

**Comment by samreid** [comment]
Discovered in https://github.com/phetsims/qa/issues/1079

**Comment by KatieWoe** [comment]
Looks good in rc.3
