### ISSUE TITLE
Preferences query parameter strings should match preferences menu labels

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#322]
When building the teacher tips, I noticed that the query parameters for 'binStrategy' and 'launchSoundStrategy' did not match the labels used in the Preferences menu. Let's change these to 'histogramBins' and 'launchSound' so that they match the UI.

**Comment by matthew-blackman** [comment]
Please close after confirming that this is fixed.

**Comment by kathy-phet** [comment]
Good catch, @matthew-blackman

**Comment by matthew-blackman** [comment]
This has been fixed and cherry picked into 1.0. Closing.
