### ISSUE TITLE
Unwanted parameter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#323]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1083
`histogramBins=totalBins` should not be available in PDL, but the parameter works and changes the bin strategy. `projectileTypeAffectsSpeed` and `showStandardError` also do not apply, but I can't tell if they are present because if they are they make no noticeable changes on the sim.

**Visuals**
![works](https://github.com/phetsims/projectile-data-lab/assets/41024075/df3d874e-d48d-4348-b0b5-01ab64a02cb3)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Projectile Sampling Distributions‬
URL: https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.0-rc.7/phet/projectile-sampling-distributions_all_phet.html
Version: 1.0.0-rc.7 2024-05-02 19:37:47 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by matthew-blackman** [comment]
This has been fixed in the commit. @samreid and I agreed that it if a user were to add `histogramBins=totalBins` to the PSD sim, we want to display the 'Invalid Query Parameters' dialog. This is not the case with `projectileTypeAffectsSpeed` and `showStandardError`, since these have no impact on the PSD sim.

**Comment by KatieWoe** [comment]
Looks good to me
