### ISSUE TITLE
Histogram count axis scaling zoom levels

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#33]
@matthew-blackman and I requested feedback on the histogram vertical axis scale for the zoom levels, and @catherinecarter said she would take a look. Thanks!

**Comment by samreid** [comment]
@matthew-blackman is this duplicate of https://github.com/phetsims/projectile-data-lab/issues/26?

**Comment by matthew-blackman** [comment]
This work is being tracked in #26. Closing.
