### ISSUE TITLE
FieldIO instrumentation simplifications

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#330]
PDL was used as an exemplar for instrumenting Gas Properties. While working on https://github.com/phetsims/gas-properties/issues/77 and https://github.com/phetsims/gas-properties/issues/231 with @zepumph, we noted the following things about the implementation of FieldIO:

- [x] `toStateObject` is unnecessary. The default implementation that is derived from stateSchema does the same thing.
- [x] `defaultDeserializationMethod` is unnecessary. (Ask @zepumph why.)
- [x] `applyState` would be unnecessary if stateSchema used `ReferenceArrayIO` instead of `ArrayIO`. See ReferenceArrayIO's default applyState (line 37).

According to @zepumph, the above changes will change the PhET-iO API, but will not require migration processors.

**Comment by samreid** [comment]
I applied the changes above and tested in the state wrapper (I tested a VSM screen and the sampling screen). Seems to be working OK. @matthew-blackman can you please review/test?

**Comment by matthew-blackman** [comment]
Reviewed and tested. This is working well and the code looks great. Nice job! Closing.
