### ISSUE TITLE
CT: Cannot set values directly to a non-bidirectional DynamicProperty, tried to set: 1.2

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#331]
Flagged in the migration wrapper

**Comment by samreid** [comment]
@matthew-blackman and I observed that the Field property was bidirectional, but the property it was wrapping was a DynamicProperty that was bidirectional:false, so we would like to make the related properties bidirectional and see how that fares on CT.  Committed above and let's check on CT in a few days.

**Comment by matthew-blackman** [comment]
CT has been green since the latest commit. @samreid and I agreed that this issue can be closed. Nice work!
