### ISSUE TITLE
[CODAP] Errors in console when adding variables to Graph

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#341]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1096, on any screen:
Dragging 'Launch Speed' and 'Launch Angle' to the graph's axes causes errors to appear in the console. 

**Steps to reproduce**
1. While on any screen, check all variables under "measurement"
2. In either order, drag 'Launch Speed' and 'Launch Angle to the graph's axes.

**Visuals**
<img width="971" alt="Screenshot 2024-06-18 at 3 00 39 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/36aa5dd7-888a-4d29-a6bb-236e284c3c8b">

**Comment by matthew-blackman** [comment]
This appears to be an issue in CODAP. I am getting the same console error when I open a blank CODAP document, create an empty graph and data table, make 2 new attributes and then drag them to the graph axes. It doesn't appear to create any problems when there is data available, but does log an error in the console when there is none.

Here is the blank file template for CODAP: closed.https://codap.concord.org/app/static/dg/en/cert/index.html

@Nancy-Salpepi can you confirm that this also happens for you in a blank CODAP file? If so, this issue can be closed.

**Comment by Nancy-Salpepi** [comment]
It does happen using the link you sent me. 
Closing.
