### ISSUE TITLE
[CODAP] Wrapper should not reveal mystery launcher mechanism and angle stability

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#348]
One of the exemplar lessons that we have designed for the PDL + CODAP wrapper has students investigating the mechanisms and angle stabilities of mystery launchers. Allowing them to directly access the 'Launch mechanism' and 'Angle stability' of the mystery launchers can undermine these lessons. It makes sense to include these values in the data stream for the custom launchers, but for the mystery launchers it would be better to give a value of '?' for these two quantities, since those are the 'mystery' of the mystery launchers.

**Comment by matthew-blackman** [comment]
Note: This feature was requested and has been approved by HL's group. I really like the fact that it lets students 'solve' for the properties of the mystery launchers without needing to hide these variables. @catherinecarter are you okay with this change? If so I think this issue can be closed.

**Comment by catherinecarter** [comment]
I think it's ok. I also thought giving that information away might be too much. I do, however, think that the documentation for how to include it as a query parameter needs to be accessible for users (specifically teachers). 

Can we include this in the dialog box that pops up when the sim opens, towards the bottom? Students are less likely to read the whole thing. Not many teachers (even power users) know about (and use) query parameters, so adding this to be more visible seems like a good idea.

**Comment by matthew-blackman** [comment]
Thanks @catherinecarter, continuing that discussion in https://github.com/phetsims/projectile-data-lab/issues/350. This issue can be closed.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.1. I see "?" for the launcher mechanism and angle stability with mystery launchers.
