### ISSUE TITLE
[CODAP] Name of sample size in CODAP is strange

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#352]
In reviewing #344, I noticed the naming of the sample size is strange: 
![image](https://github.com/user-attachments/assets/13278109-35e5-46ac-a5cc-668d7797bdb4)

Is there any way to remove the extra "Field" next to the sample size (and just show the same size)?

**Comment by matthew-blackman** [comment]
@catherinecarter nice find! It is fixed in the commit and sample size is now a number and is being treated as numeric by CODAP. It was very straightforward and I think this issue can be closed. Please reopen if anything else comes up in this area.

**Comment by catherinecarter** [comment]
Looks good. The numbers show up horizontally, too, which is really nice. I wasn't expecting it to do that, but I'm glad it does. Thanks!
