### ISSUE TITLE
Projectile selector panel improvements

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#38]
The projectile selector panel needs the following improvements:

- Add an icon to show the launcher used.
- Layout and image size redesign
- Check for consistency with sample selector panel

**Comment by samreid** [comment]
I don't feel I know enough about the vision for this to start on it independently, @matthew-blackman can you work on it or provide a mock-up, or discuss it with me to get me started?

**Comment by matthew-blackman** [comment]
From the 1/5 design meeting:

- Add icon for launcher at correct configured angle
- Remove outer panel from projectile selector
- Remove 'go to first', 'go to last' buttons

From 1/8 check-in with AP

- Separate highlights for most recent and selected projectile
- Secondary differentiator for highlighted/most recent
- Mimic selected highlight in panel
- Catching up to most recent projectile brings back into live mode
- Remove outer panel of projectile selector

**Comment by samreid** [comment]
From today's design meeting, we confirmed we want to add the launcher icon into the projectile card.

**Comment by matthew-blackman** [comment]
Remaining work here is being tracked in https://github.com/phetsims/projectile-data-lab/issues/92. Closing.
