### ISSUE TITLE
Finalizing mystery launcher design

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#43]
The mystery launchers are currently color-coded and labeled by number. Do we want to modify the design of the mystery launchers for production?

One suggestion was to have a distinct pattern for each mystery launcher, such as polka dots, stripes, or a sunburst shape on the nozzle similar to the classic projectile motion launcher.

**Comment by matthew-blackman** [comment]
Ways to differentiate launchers:

1) Color
2) Number label
3) Pattern on the launcher barrel (polka dots, stripes, sunburst shape similar to Projectile Motion launcher)
4) The shape of the launcher barrel itself (nozzle width, barrel shape rounded vs polygon, etc)
5) Differences in the launcher frame or guide rail.

**Comment by matthew-blackman** [comment]
Let's get input from HL before proceeding with the design.

**Comment by matthew-blackman** [comment]
From 1/10 check-in with HL:

"My gut feeling right now is that we should not have a visual representation of that (the physical properties of the mystery launchers). Those learning goals addressed on the other screen (Sources). And this one (Variability) is really this idea of trying to understand what this cannon is based on the data instead of the visual representation. That's my gut feeling"

**Comment by samreid** [comment]
Meeting Notes Jan 12, 2024 - Development check-in.

@matthew-blackman will reach out to @mariahmaephet for ideas for artwork to distinguish between the launchers. We will not have semantic clues as to the mechanisms or distributions, just different ways to visually distinguish them. My understanding is this will include patterns/decals/colors. Not sure if it also includes differing shapes.

**Comment by matthew-blackman** [comment]
In the 2/8 and 2/15 design meetings, we decided on the following designs for the mystery launchers:
<img width="731" alt="MysteryLaunchers" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/98f0ad62-5501-4952-ada9-38effb953ad6">

Let's use the existing graphics system in LauncherNode for the barrel gradient and frame, but add the patterns as svgs.

**Comment by matthew-blackman** [comment]
The graphics are in and ready for review. @samreid I have the custom launcher using mystery launcher index 7 currently. Probably not the best for production but let's discuss how to improve. Over to you!

**Comment by samreid** [comment]
@matthew-blackman and I determined 3 problems related to having a blank SVG file. We decided to remove the SVG file. Will check on CT to see if that resolves the _.maxBy problem and the width not defined problem.

**Comment by matthew-blackman** [comment]
The mystery launchers are looking great! The team has signed off on the designs and colors, and remaining dev work is being done over in https://github.com/phetsims/projectile-data-lab/issues/168. Closing. Nice work!
