### ISSUE TITLE
Accessibility features and improvements

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#44]
This issue is for tracking the remaining development work to implement accessibility features and improvements.

The following checkboxes were copied from https://github.com/phetsims/projectile-data-lab/issues/44#issuecomment-1879083609 on Jan 9, 2024 in order to convert them into side issues:

- [x] #60
- [ ] #61
- [x] #62
- [x] #63
- [ ] #64
- [x] #65

**Comment by samreid** [comment]
Notes from meeting with @terracoda today:

Should the launch button be focused first?

**Comment by samreid** [comment]
I'll work on this issue, removing other assignees for now.

**Comment by samreid** [comment]
I converted the recommendations into checkboxes above, but I feel it would be even better to turn them into separate issues. I think I will try to do this by moving them to the top comment first, then letting GitHub help with the issue creation.

**Comment by samreid** [comment]
I moved all of the known recommendations for this issue into side issues (see the top comment). @matthew-blackman can you please skim this issue and see if I missed anything? If not, this issue can be closed.

**Comment by matthew-blackman** [comment]
Let's complete the side issues listed in the checklist at the top of this issue, and check in with @terracoda once they are ready to review.

**Comment by samreid** [comment]
All above issues are closed or ready for design review. @matthew-blackman is this ready to bring back to @terracoda ?

**Comment by matthew-blackman** [comment]
We are tracking the remaining work here in #61 and #64. This issue can be closed.
