### ISSUE TITLE
Making fields more distinct

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#46]
In several discussions, it has come up that the fields look very similar, making it difficult to differentiate them. This is especially notable with fields that have no data.

In order to make it more clear how the fields work, let's discuss ways to make them visually distinct without being distracting. Some ideas to consider:

1) Different visual design for the field sign on each field.
2) A "scenery" object associated with each field (tree, background, objects on the side of the field, etc)
3) The color of the field itself.

**Comment by samreid** [comment]
@matthew-blackman commented that animating translation behavior to switch fields would interfere with the "switch back and forth between 2 fields to easily compare them" design goal.

**Comment by samreid** [comment]
@matthew-blackman closed https://github.com/phetsims/projectile-data-lab/issues/97, can this one also be closed?

**Comment by matthew-blackman** [comment]
Differentiating fields based on color is a promising approach, and is preferable to adding artwork to the fields. I checked in with @ariel-phet, @arouinfar and @catherinecarter on this and all agreed that the colors can be fine-tuned as part of https://github.com/phetsims/projectile-data-lab/issues/83. Let's continue over there. This issue can be closed. Nice work all!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by matthew-blackman** [comment]
The field colors have been updated and tested with low-contrast and monochrome filters. This is looking good! Discussed with @catherinecarter and @ariel-phet and they agrees this is in a good place. This issue can be closed, feel free to reopen if you feel otherwise.
