### ISSUE TITLE
Data measures display improvements

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#49]
In a student interview, @catherinecarter noted that the student was not able to distinguish the meaning from data measures display. We want to make sure that students are able to gather that it is showing the mean and standard deviation of the data.

**Comment by samreid** [comment]
Will this be solved by #52 ?

**Comment by matthew-blackman** [comment]
@catherinecarter agreed to wireframe the layout of the data measures display with mean and standard deviation labels. Thanks Cathy!

**Comment by matthew-blackman** [comment]
> Will this be solved by #52 ?

Let's use #52 to track dev progress on splitting up the checkboxes, and this issue for design improvements of the data measures display.

**Comment by catherinecarter** [comment]
What do you think about something like this? (Clearly the field is just a quick green rectangle and not the actual field.)
<img width="381" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/2c547ccb-62b7-41c0-bd3b-1a177649b25b">
 
And if the SD were small, it could look something like this?
<img width="240" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/afd2ea17-d8c4-45cb-a7ba-1dd8c6f1f26e">

Or there could be a semi-transparent rectangle behind the mean but in front of the left/right vertical lines if the mean value got lost: 
<img width="400" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/476924b2-9ce9-4b22-b299-6581eb860e23">
<img width="327" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/cd5133a2-a95d-4291-9bf1-94f85f281a3e">

In terms of overlapping with the values on the measurement tool, I'm wondering if, in the example below, the 11.3m could shift down slightly, and the percentage could go above the 11.3m? That might add some space above the mean triangle and SD readouts.

It's a first pass. What do you think?

**Comment by matthew-blackman** [comment]
These are great - thank you @catherinecarter! I prefer the version with the background rectangle to avoid overlapping lines and numbers. How do you feel about making the rectangle a solid color (maybe an off-white) with no transparency to improve readability of the mean? In the last screenshot you shared, if the SD was a bit smaller the vertical lines going behind the mean could make it hard to read.

In context of the work being tracked in https://github.com/phetsims/projectile-data-lab/issues/52, here is how it would look with separate toggles for the mean and SD:

![image](https://github.com/phetsims/projectile-data-lab/assets/108756567/5861323b-0869-4db5-bfc0-8fb2facbdc18)

![image](https://github.com/phetsims/projectile-data-lab/assets/108756567/77f77774-140a-466b-a4ed-f361ea6f4163)

Thoughts @catherinecarter?

**Comment by samreid** [comment]
@matthew-blackman and I added some commits that improve the behavior under i18n.

**Comment by catherinecarter** [comment]
The data measures visuals and readouts look great. The only thing I noticed is how close the SD arrows are to the top of the vertical lines. In the histogram, it reminds me of a churn or something. The shape looks like a rectangle rather than vertical lines with measures spanning from the middle. 

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/9467a583-cfe9-4584-93d9-7b264ff77e84)
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/a16a6569-c64b-4a42-ba9d-950126a3dae7)

Can we either bring the arrows down, thin them up a bit (the line between the arrows is bleeding into the arrows a little, especially for small SD), or a combo of both?

**Comment by catherinecarter** [comment]
I was playing with the sim this morning using launcher 6 at 0º and was able to get the left edge of the SD measure line to overlap with the output display in the upper left:
<img width="765" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/216534d5-c163-4a02-9c85-ead60ffcfeac">

Do we want to revisit the height of those SD vertical lines, along with the position of the arrows? The arrows are pretty lined up with the bottom edge of the readout box.

**Comment by matthew-blackman** [comment]
This is ready for review @catherinecarter!

List of updates:
- Info panel in front of data measures in histogram
- Thickness of SD 'side lines' is thinner than mean line
- SD must be greater than zero to showing SD 'side lines'
- Show SD values even when SD = 0
- SD arrow proportions and scaling
- Height of SD 'side lines' in histogram
- y-position of SD arrows in histogram

Note to self: Hitting the Clear button should hide the SD text and mean line. This still needs to be implemented.

**Comment by matthew-blackman** [comment]
@catherinecarter signed off on the updates listed above and recommended that when the SD is smaller than 1, we could represent it with line segments instead of arrows. Let's implement this, and also try using color on the lines/arrows to convey that they are they represent the same quantity.

**Comment by matthew-blackman** [comment]
The latest commit has been reviewed and signed off on by myself and @catherinecarter. Nice work! Closing.
