### ISSUE TITLE
Create launch panel

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#5]
Tracking the construction of the launch panel, which is used to control the launcher apparatus and projectiles. It will need to conform to the following designs for each screen:

Variability screen:
![LaunchPanelVariability](https://github.com/phetsims/projectile-data-lab/assets/108756567/d4d1ce98-86cf-4b10-bd07-2e16351da6cc)

Sources screen:
![LaunchPanelSources](https://github.com/phetsims/projectile-data-lab/assets/108756567/e8435155-d1ab-49f1-8d57-65fc77e68502)

Measures screen (standard launcher):
![LaunchPanelMeasures1](https://github.com/phetsims/projectile-data-lab/assets/108756567/b2ec9cfc-6857-444f-8740-8f863ceaabe7)
Measures screen (custom launcher):
![LaunchPanelMeasures2](https://github.com/phetsims/projectile-data-lab/assets/108756567/aaabd769-7c18-44df-94fb-5f5b20cb19a0)

Sampling screen
![LaunchPanelSampling](https://github.com/phetsims/projectile-data-lab/assets/108756567/1bd89b1c-80db-48fc-80d2-7244f0c841d7)

**Comment by samreid** [comment]
This issue hasn't been worked on since Nov 19, and I'm not aware of any further work in this area that is not noted in the Google doc. Closing, @matthew-blackman please reopen if there is more for this issue.
