### ISSUE TITLE
Make histogram size consistent across all screens

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#50]
The histogram should be consistent in position and size across all screens. The sampling distribution size is correct, and the VSM screen histogtams should be increased to match it.

**Comment by samreid** [comment]
Here is an overlay that shows the Variability screen and the Sampling screen. There is another recommendation for making the checkbox icons smaller, but I don't know if that will be enough to compensate:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/93de2c2a-f14d-4537-b420-a4c4fe2c9942)

**Comment by matthew-blackman** [comment]
Thanks @samreid for the screenshot! 

In the horizontal dimension, since we are constrained by the width of the right-side panels in VSM screens, let's try increasing the width of the histogram thumbnails on the Sampling screen and decreasing the width of the Sampling HistogramNode.

In the vertical dimension, let's try using a height that is between the current height of the VSM and Sampling histograms. We may nee to shrink the Sampling thumbnails a little bit, so let's check in with @catherinecarter on how much would be a good compromise here.

**Comment by samreid** [comment]
This should be in exactly the same spot and same dimensions.  So we may need to choose the size/position of the chart rectangle and flow things around it.

**Comment by samreid** [comment]
Things are mostly good here. Some possible next steps for collaboration:

- [ ] Long strings expand the left panel too much, it looks related to the margins (see the scenery helper).
<img width="297" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/d760c85c-a09c-4ec9-b084-15152b9091b5">

- [ ] These aren't exactly top aligned, it is more by luck. There is a TODO for this.
<img width="188" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/96842756-94b2-412c-a0b1-c5e04d98cf49">

Let's touch base.

**Comment by samreid** [comment]
Fixed, closing.
