### ISSUE TITLE
Launcher angle sometimes carries over onto new field

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#51]
This is likely related to https://github.com/phetsims/projectile-data-lab/issues/28 and should be tested after that issue is worked on.

Steps to reproduce:

1) Set launcher to configuration 4
2) Begin continuous launching
3) Switch back and forth between fields 1 and 2 until the launcher angle appears horizontal in field 2

**Comment by samreid** [comment]
It looks like this was caused by the barrel rotation Animation still being in progress. I canceled in when the field changes and it seems fixed. @matthew-blackman can you please review and verify?

**Comment by matthew-blackman** [comment]
It looks like the animation issue is mostly fixed - nice work! I am still seeing one remaining behavior where if the launcher is just fired, and then the field is switched to another field with the same configuration, the angle of the previous launcher gets applied to the new field. In this recording, I had Launcher 2 continuous launching on Field 1, and Launcher 1 idle on Field 2. Switching from Field 1 to Field 2 immediately following a launch causes the angle of the launcher on Field 1 to be applied to Field 2:

https://github.com/phetsims/projectile-data-lab/assets/108756567/a1362976-31d3-4a0d-8a96-68b4c3f755ba

I will investigate this.

**Comment by matthew-blackman** [comment]
@samreid and I noticed the same problem when switching configuration immediately after a launch.  Both bugs have been addressed in the above commits and reviewed. Closing.
