### ISSUE TITLE
Data measures display - Separate checkboxes for mean and standard deviation

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#52]
In the 1/5 design meeting, the design team decided to split up the data measures display into separate checkboxes for 'Mean' and 'Standard deviation'. Let's implement this.

**Comment by matthew-blackman** [comment]
@catherinecarter agreed to wireframe the layout of the data measures display with mean and standard deviation labels. Thanks Cathy!

**Comment by samreid** [comment]
This was also discussed at today's design meeting. @matthew-blackman can you please describe the proposed design?

**Comment by catherinecarter** [comment]
Love them! Further comments as the boxes are connected to the "Values" checkbox in issue #81.

**Comment by samreid** [comment]
@matthew-blackman and I reviewed this today. I had a few design comments. The code review looks good.

* The standard deviation label has a shrunken font. Should we split it into 2 lines or adjust the fonts?
* Should we show the values below the histogram if the histogram is collapsed?

**Comment by matthew-blackman** [comment]
Let's shrink the checkboxes smaller than their default size, and also see if the icons on the right side of the panel can be reduced in size. If we can get the text so that it doesn't shrink in English, that should be good enough.

**Comment by samreid** [comment]
This is looking better:

<img width="206" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/3505031f-cc17-4c11-9d1f-fd00448fbde9">

We can adjust further as desired, and there are some related problems listed in https://github.com/phetsims/projectile-data-lab/issues/50#issuecomment-1905127130

**Comment by matthew-blackman** [comment]
This issue has been reviewed, and the design and code are looking great. Nice work! Closing.
