### ISSUE TITLE
Update configuration icons to match launcher design

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#53]
From the 1/5 design meeting: Update configuration icons to match the new look of the launcher.

I can mock up configuration icons that are more similar to the launcher design. To avoid having to choose a launcher, it should be designed so that it applies to all of the launchers.

**Comment by matthew-blackman** [comment]
Let's try to simplify the design here. We really just want to convey the angle and height, and don't necessarily need to add more launcher icons to the sim. @ariel-phet how would you feel about something like this as a rough mockup of a possible direction to pursue?
<img width="226" alt="Screen Shot 2024-02-13 at 3 34 45 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/4d7cf250-a629-4a33-ae1d-d73879cc6b44">

**Comment by ariel-phet** [comment]
@matthew-blackman I think this is a really nice improvement to the sim. It puts the focus on the launch height and angle in a very uncluttered way that works for all launchers. I like the cleanliness aspect quite a bit, considering just how much we visually have on the screen. Nice job!

**Comment by matthew-blackman** [comment]
I updated the icons and added svgs instead of drawing them with scenery. The part where the arrow touched the horizontal line had some visual detail that would have required using a mask with the arrow, so I think svg's are a better option. Let me know if you agree @samreid.

**Comment by samreid** [comment]
The icons and the code changes look great. I feel this issue can be closed. Nice work @matthew-blackman

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
