### ISSUE TITLE
Rename 'single' and 'continuous' sampling modes

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#55]
We would like to simplify the names of the launch modes on the Sampling screen to 'Single' and 'Continuous' in the UI.

**Comment by samreid** [comment]
Renamed above. Let's make sure that is the desired direction before removing the other strings and consolidating duplicated string code at the usage sites.

**Comment by matthew-blackman** [comment]
@catherinecarter can you confirm that these strings are now correct?

**Comment by matthew-blackman** [comment]
This looks good, closing.
