### ISSUE TITLE
Finalize values for launcher speed, speed SD and angle SD

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#56]
This applies to both the mystery launchers and the custom launcher.

**Comment by samreid** [comment]
One of our collaborators was going to look at this and report back, and we saw that some or all of these properties are phet-io instrumented, but at least some are currently read-only.

**Comment by matthew-blackman** [comment]
I collaborated with @joeyliu95511 on this and discussed values that would support his research with HL. We discussed the following points:
- He wants the launch mechanisms to all have different mean speeds, to allow students to compare the means (since they cannot do this by adjusting the angle stabilizer)
- We don't want to provide students with a false correlation between mean speed and SD of speed. To prevent this, we want to make sure that the mean and SD speeds are not chosen to give the idea that they are correlated.

We adjusted the values for the three mechanisms and came up with a progression that we felt provides good modes of inquiry for students. Here are the values we agreed upon:

Spring:
Mean: 23 m/s
SD: 0.5 m/s

Pressure:
Mean: 24 m/s
SD: 0.2 m/s

Explosion:
Mean: 25 m/s
SD: 1.2 m/s

Here are images of three distributions we obtained with these values:
<img width="1158" alt="Screen Shot 2024-03-01 at 3 42 13 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/9187dd5a-57de-4fa8-a19b-f3980d70509e">
<img width="1158" alt="Screen Shot 2024-03-01 at 3 42 16 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/5e00ac68-2caf-4fea-ba48-16895decad8c">
<img width="1158" alt="Screen Shot 2024-03-01 at 3 42 19 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/e18b7847-1b49-430c-b949-3901a21d9c60">

**Comment by catherinecarter** [comment]
After playing a bit, the variability of the landing positions is really nice for launcher 1, especially on bin width = 1.

**Comment by matthew-blackman** [comment]
After feedback from the design team and our research partners, we decided upon the following values:

Spring:
Speed mean: 23 m/s
Speed SD: 0.5 m/s

Pressure:
Speed mean: 24 m/s
Speed SD: 0.2 m/s

Explosion:
Speed mean: 25 m/s
Speed SD: 1.2 m/s

These values provide a good combination of varying means and standard deviations, and create interesting avenues for students to explore the similarities and differences between the mechanisms.

The mystery launchers are as follows:

Mystery launcher 1:
Spring
Angle stabilizer: 50%

Mystery launcher 2:
Pressure
Angle stabilizer: 0%

Mystery launcher 3:
Explosion
Angle stabilizer: 100%

Mystery launcher 4:
Spring
Angle stabilizer: 25%

Mystery launcher 5:
Pressure
Angle stabilizer: 100%

Mystery launcher 6:
Explosion
Angle stabilizer: 0%

These mystery launchers create a sequence in which students explore the launch angle and speed in modular steps. It is also nice that launcher 5 is the most precise, rather than launcher 1.

Nice work all! This issue can be closed.
