### ISSUE TITLE
CODAP wrapper development

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#6]
We should look at projectile motion or circuit construction kit for an existing wrapper. May need an HTTPS server. Let's set up the initial scaffolding and decide how much code should be centralized/factored out vs how much should be project-specific.

**Comment by samreid** [comment]
After the changes above, the sim loads in CODAP at https://codap.concord.org/releases/dsg/static/dg/en/cert/index.html?di=http://127.0.0.1:8123/phet-io-sim-specific/repos/projectile-data-lab/wrappers/codap?sim=projectile-data-lab

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/621a936e-fd91-42d0-9d8f-64bf90ca99f7)

**Comment by samreid** [comment]
@matthew-blackman said the CODAP development is feature complete and we can make changes after review in the design meetings. That work will be done elsewhere. Closing.

**Comment by zepumph** [comment]
@samreid, should we revert https://github.com/phetsims/chipper/commit/aeb968c45bbd911c8b54ca9239f58810606670d7?

**Comment by samreid** [comment]
I pushed the revert, thanks! Closing.
