### ISSUE TITLE
Should the projectile selector panel have a title or heading?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#65]

**Comment by matthew-blackman** [comment]
The design team agreed that the selector panels look good without a background fill or stroke. Since the contents are self-explanatory and with this "floating" design, a title/heading is not necessary. Closing.

**Comment by terracoda** [comment]
If you think about what you want these selector panels to called now, you won't have to do it later when you want to add Voicing or other forms of description.

**Comment by matthew-blackman** [comment]
Is it enough to document that we refer to it as the 'projectile selector' in the code and design docs? The design team was in favor of a lighter weight design for this component, without a panel background or heading (see screenshot)

<img width="265" alt="ProjectileSelector" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/81a11fff-c5ac-4bc7-aa25-3944be2ba502">
