### ISSUE TITLE
Convert selector panels to NumberSpinner

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#66]
The projectile selector and sample selector are recreating some of the functionality of NumberSpinner, but without the desired alt input support patterns. We decided to rebuild the ProjectileSelectorPanel and SampleSelectorPanel components as extensions of NumberSpinner.

This is connected to the work being done in https://github.com/phetsims/projectile-data-lab/issues/38 and https://github.com/phetsims/projectile-data-lab/issues/59 and https://github.com/phetsims/projectile-data-lab/issues/67

**Comment by samreid** [comment]
OK I converted the projectile selector and sample selector to use a new type SelectorNode that was adapted and simplified from NumberSpinner, and which uses AccessibleNumberSpinner. It seems to be working well. It would be good to check in with @matthew-blackman for a brief review.

**Comment by samreid** [comment]
We finished reviewing and everything seems good. Closing.
