### ISSUE TITLE
Add launcher icon to ProjectileSelectorPanel card

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#67]
In the 1/9 design meeting, we confirmed that we want to add an icon to the ProjectileSelectorPanel card, showing the state of the launcher when a projectile was fired. Let's use LauncherNode to create this icon from the graphics in the launcher itself.

This is part of the work being done in https://github.com/phetsims/projectile-data-lab/issues/38.

**Comment by samreid** [comment]
I wrote to slack dev-public:

> In today’s design meeting, it was recommended that Projectile Data Lab use a left/right NumberSpinner to select between the projectiles or samples (we currently have a custom component that doesn’t support all of the keyboard interactions that NumberSpinner does). However, we were also recommended to put an icon in that readout. Is this possible? How should we proceed?  The current panel looks like this, and the demo from sun for the left/right spinner looks like this

**Comment by samreid** [comment]
@pixelzoom said:

> NumberSpinner does not support this - and I do not recommend adding to NumberSpinner. You’ll likely need to write something custom, or push back on the design request. You might also have a look at ObjectPicker (can’t recall which sim), a variant of NumberPicker for use with non-numbers.

**Comment by samreid** [comment]
In #66 I created a custom component that duplicates NumberSpinner functionality, and will be more amenable to showing icons.

**Comment by samreid** [comment]
I started crafting specific types, but there is way too much boilerplate and complexity to make it worth it. Here is a paper trail in case we go back to it:

```
type LauncherType = {
  type: 'mystery';
  launcher: number;
} | {
  type: 'custom';
  mechanism: 'spring' | 'pressure' | 'explosion';
  angleStabilizer: number;
};

public static MysteryLauncherIO = new IOType( 'MysteryLauncherIO', {
  valueType: Object,
  stateSchema: {
    type: StringUnionIO( [ 'mystery' ] ),
    launcher: NumberIO
  },
  toStateObject: ( launcherType: LauncherType ) => {
    return launcherType;
  },
  fromStateObject: ( stateObject: LauncherType ) => {
    return stateObject;
  }
} );

public static CustomLauncherIO = new IOType( 'CustomLauncherIO', {
  valueType: Object,
  stateSchema: {
    type: StringUnionIO( [ 'custom' ] ),
    mechanism: StringUnionIO( [ 'spring', 'pressure', 'explosion' ] ),
    angleStabilizer: NumberIO
  },
  toStateObject: ( launcherType: LauncherType ) => {
    return launcherType;
  },
  fromStateObject: ( stateObject: LauncherType ) => {
    return stateObject;
  }
} );

public static ProjectileIO = new IOType<Projectile, ProjectileStateObject>( 'ProjectileIO', {
  valueType: Projectile,
  stateSchema: {
    screenIdentifier: StringUnionIO( ScreenIdentifierValues ),
    fieldIdentifier: StringIO,
    sampleNumber: NumberIO,
    launcherConfigurationAngle: NumberIO,
    launcherType: OrIO( [ Projectile.MysteryLauncherIO, Projectile.CustomLauncherIO ] ),
```

Note the `OrIO` which is less frequently used.

**Comment by samreid** [comment]
I made progress on this, listed several TODOs, and would like to check in with @matthew-blackman synchronously.

**Comment by samreid** [comment]
We met about this today and made some progress. We agreed to add a mystery vs custom enumeration. @matthew-blackman suggested the name "LauncherCategory" or "LauncherCategoryType". I can work on that part, then I'll bring it back for collaboration and review in the remaining TODOs in the code.

**Comment by samreid** [comment]
I decided to call it `MysteryOrCustom` and I implemented it in the commit.

**Comment by samreid** [comment]
We renamed it to `MysteryOrCustom` and all the TODOs in the code are addressed. Closing.
