### ISSUE TITLE
Update projectile selector UX

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#69]
During the 1/9 design meeting, we agreed to implement the following improvements to the projectile selector panel.

- Disable the projectile selector buttons when the field is unpaused with airborne projectiles.
- Enable the projectile selector buttons when the field is paused.
- When a projectile lands, it should become selected.
- Merge button enabled state to also account for the index of the selected projectile and the total number of landed projectiles.

This is part of the work being done in https://github.com/phetsims/projectile-data-lab/issues/38

**Comment by samreid** [comment]
All ready for feedback except:

- [ ] When a projectile lands, it should become selected.

**Comment by samreid** [comment]
Fixed. I worked on most of the implementation with @matthew-blackman. The last step https://github.com/phetsims/projectile-data-lab/commit/16593a1dee94af5a3290d53e40bd76ebd3509eca was easy, and actually simplified existing code. So this is ready for review. But even if the review is good, we may want to hold off until Friday to see if the play/pause button is going to disappear.

**Comment by samreid** [comment]
From the Meeting Notes Jan 12, 2024 - Development check-in, we would like to make the enabled buttons to look more opaque.

**Comment by matthew-blackman** [comment]
This is ready for review. @catherinecarter what do think of the updated selector buttons?

**Comment by matthew-blackman** [comment]
@catherinecarter agreed that the button colors look good, and recommended checking for color contrast, etc.

@samreid @catherinecarter and I also agree that the projectile card should not change size with new data. Let's make the card big enough to support the largest icons/numbers and leave whitespace for the smaller ones.

Tracking that remaining work in https://github.com/phetsims/projectile-data-lab/issues/84 and closing.
