### ISSUE TITLE
Should the Sampling screen have time controls?

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#71]
During a design check-in, @catherinecarter proposed a 'Fast' mode in the 'single launch' on the Sampling screen. Some thoughts:

- Launching a single sample supports the learning goals of understanding sample collection and mean.
- Collecting a single sample takes several seconds, with more time for larger samples.
- Speeding up a Single sample could provide the benefits of Single sample mode, along with the benefits of faster data collection.

This would only apply to single sample and not continuous.

Note: We are not recommending any changes to the overall UX of single and continuous modes.

**Comment by matthew-blackman** [comment]
This was straightforward to implement in the Sampling screen and seemed valuable to try. Seeing the mockup, the time controls appears to have significant value in this screen. Each combination of Single/Continuous and Normal/Fast offers a unique pedagogical value:

- Single mode, Normal speed is good for showing realtime behavior and taking in the individual values that contribute to the mean.
- Single mode, Fast speed is good for showing the same and mean more quickly, to digest the sample as a whole. This is especially useful in the larger sample sizes.
- Continuous mode, Normal speed is good for taking in the values of each mean, as they vary on the field.
- Continuous mode, Fast speed is good for amassing a full data set quickly.

Note: I also adjusted the time interval for Continuous mode from 0.15 to 0.4, so that the Normal and Fast each felt like distinct speeds, as opposed to both feeling fast.

@catherinecarter would love to get your thoughts on this feature!

**Comment by catherinecarter** [comment]
I love these controls! 

**Timing**
I feel like the timing of the "fast" mode on single sample is a bit fast. It's difficult to tell how many projectiles are actually being launched. 

**Behavior**
I'm sure this will be addressed, but I was able to pause the sim, press launch, and the sim remained pause. For consistency, let's have the sim launch a sample when the sim has been paused and the user presses 'launch.'

**Comment by matthew-blackman** [comment]
Thanks @catherinecarter! I think we are good to proceed with this feature. @samreid I implemented a fix in the above commit for the 'Launch when paused' issue that CC mentioned above. It is working well in my testing but I feel that a better solution may come out of work in https://github.com/phetsims/projectile-data-lab/issues/22. 

Can you review the above commits?

**Comment by samreid** [comment]
The commits and runtime behavior look great, nice work.  I feel the UX is a little confusing in certain circumstances, such as:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/52a54b8a-6c30-47e9-8c4e-d60dafa6d4fd)
Figure 1: From the user's point of view, there are two "go" buttons, but they do very different things.

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/e064fc7b-8762-45a0-8aa4-f6c8772b7db9)
Figure 2: Now there are 2 "stop" buttons that do very similar things.

Generally, there are 4 states you can be in for continuous mode: 
* Start | Start
* Start | Stop
* Stop | Start
* Stop | Stop

I do not have a better recommendation and I do not think these corner cases should prevent us from publishing with this feature (since it is generally for the better). Nor do I think it would be an improvement to remove the play/pause button, since it is nice to have it with the speed radio buttons. Nor do I think we should wire up the play/pause button to also control the launch button. I just wanted to point out some cases that the user will likely need to experiment with and figure out.

@catherinecarter can you please review the new behavior?

**Comment by matthew-blackman** [comment]
Notes from meeting with @catherinecarter and @samreid 1/18

- We want to keep the time controls on the Sampling screen
- Time controls should have a consistent position across all 4 screens
- Centering time controls above field sign would work for all screens
- May consider moving the field sign/eraser button to improve the layout across screens

**Comment by samreid** [comment]
I started in this patch:

<details>

```diff

Subject: [PATCH] Switch launcher to custom on the Measures screen, combine isLauncherCustom with mysteryLauncher, see https://github.com/phetsims/projectile-data-lab/issues/77
---
Index: js/common-vsm/view/VSMScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common-vsm/view/VSMScreenView.ts b/js/common-vsm/view/VSMScreenView.ts
--- a/js/common-vsm/view/VSMScreenView.ts	(revision 7ccd58a8009b53d0216484f33eb4de944a59550d)
+++ b/js/common-vsm/view/VSMScreenView.ts	(date 1705627099459)
@@ -100,7 +100,7 @@
       right: this.layoutBounds.right - PDLConstants.SCREEN_VIEW_X_MARGIN,
       top: this.layoutBounds.top + PDLConstants.SCREEN_VIEW_Y_MARGIN,
       spacing: PDLConstants.INTER_PANEL_SPACING,
-      children: [ staticToolPanel, interactiveToolPanel, this.timeControlNode ]
+      children: [ staticToolPanel, interactiveToolPanel ]
     } );
 
     const accordionBoxWidth = this.topRightUIContainer.left - launchPanel.right - 2 * PDLConstants.INTER_PANEL_SPACING;
@@ -295,6 +295,7 @@
     this.toolsLayer.addChild( measuringTapeNode );
 
     this.addChild( this.projectileSelectorNode );
+    this.addChild( this.timeControlNode );
     this.addChild( this.fieldSelectorPanel );
     this.addChild( timedLaunchButton );
     this.addChild( this.accordionBox );
@@ -331,6 +332,14 @@
         projectileSelectorPanelProxy.centerX = fieldSignProxy.centerX;
       } );
 
+    // Position the time control node over the projectile selector node
+    ManualConstraint.create(
+      this,
+      [ this.timeControlNode, this.projectileSelectorNode ], ( timeControlProxy, projectileSelectorProxy ) => {
+        timeControlProxy.centerX = projectileSelectorProxy.centerX;
+        timeControlProxy.bottom = projectileSelectorProxy.top - 10;
+      } );
+
     // Position the 'No air resistance' text
     ManualConstraint.create(
       this,

```

</details>

But the layout on screen 1 is unexpectedly awkward:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/6391f0b4-5e4c-4b17-a4de-3241281a72f5)

I think I should pause and get feedback before going further.

**Comment by matthew-blackman** [comment]
After reviewing this with @catherinecarter, we agree that positioning the sampling TimeControlNode under the accordion box is promising. We would like to minimize the horizontal offset between its position on the Sampling screen, so want to try centering the TimeControlNode horizontally with the column of histogram thumbnails.

**Comment by matthew-blackman** [comment]
It has been agreed that the Sampling screen time controls are adding value to the sim and contributing to the learning goals. Let's continue tracking the remaining layout work in #39. Closing this issue.
