### ISSUE TITLE
Clicking on a UI component should focus it

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#73]
This issue was raised since you can press home/end on the projectile selector or sample selector, and @matthew-blackman and I agreed it would nice to be able to do that without having to press tab 17 times before you get there. We consulted with @jessegreenberg and he agreed it is the standard behavior such as in HTML/Aria. For instance, in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox if you click scales or horns then spacebar, it already has focus. I'm not sure how much this has been investigated or what it would take to implement this in common code. It looks like https://github.com/phetsims/joist/issues/750#issuecomment-1650537216 discusses this issue somewhat.

@matthew-blackman wanted to avoid picking and choosing individual components to have "if clicked, focus myself" and look for a more central solution.

**Comment by samreid** [comment]
@matthew-blackman want to raise https://github.com/phetsims/joist/issues/750 for discussion in a dev meeting or in slack?

**Comment by matthew-blackman** [comment]
In the sound design doc, @emily-phet brought up this issue:

> I also want to check the following with Jesse:  
Once you interact with an object with your mouse, should the focus highlight appear on the next focusable object, or back at the start (e.g., are the two inputs completely separate or not – I can’t remember).  

@jessegreenberg can you weigh in here? @samreid and I don't mind implementing 'focus on click' for components that have custom keyboard inputs, but we weren't sure if this work should be part of https://github.com/phetsims/joist/issues/750.

**Comment by matthew-blackman** [comment]
A common code solution is slated to begin work addressing https://github.com/phetsims/joist/issues/750. @samreid let's make a list of all sim-specific focusing that we have currently, so that we can remove these when #750 is resolved.

**Comment by samreid** [comment]
We currently call `.focus()` when processing input events on:

* FieldRadioButtonGroup
* MysteryLauncherRadioButtonGroupWrapper
* SelectorNode forward/back buttons

I don't think more work is necessary at this time, so I'll unassign me and @matthew-blackman.  We can check in on https://github.com/phetsims/joist/issues/750 when we get closer to QA dev test.

**Comment by samreid** [comment]
There has been no progress in https://github.com/phetsims/joist/issues/750.  Once that issue is worked on, we will adjust this simulation and other accordingly. Closing.
