### ISSUE TITLE
Change selectedSampleIndex => selectedSampleNumber

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#76]
Discovered in https://github.com/phetsims/projectile-data-lab/issues/37, we think it may be nicer to refer to selectedSampleNumber rather than selectedSampleIndex, since the number is displayed on the screen.

However, initial investigation revealed this is a very complex, and brittle change and will be a lot of work. But still probably a good move, for readability and for PhET-iO clients.

**Comment by samreid** [comment]
In working on this, there are at least 2 places with very buggy looking code that I don't understand. Let's collaborate.

**Comment by samreid** [comment]
I worked on this again, hoping it would help address https://github.com/phetsims/projectile-data-lab/issues/79. I got it working well enough that it seemed to be an improvement, even though I can't tell if there is more to do. But #79 is still not fixed, but maybe it will be easier to fix now that this is clearer.  Perhaps good to review or discuss.

**Comment by matthew-blackman** [comment]
I reviewed the code changes here and everything looks great. Nice work @samreid! After testing the behavior on the Sampling screen things are behaving well. 

Added an assertion and small rename in the above commit. Closing.
