### ISSUE TITLE
Trajectory path is slightly kinked at end

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#8]
@samreid and I noticed that the trajectory path becomes slightly kinked before the projectile lands. See below:

![Screen Shot 2023-11-22 at 1 34 44 PM](https://github.com/phetsims/projectile-data-lab/assets/108756567/fe0e05be-ce2f-4fdf-b9de-c67632c0324b)

We would like to investigate where this is coming from and fix.

**Comment by samreid** [comment]
@matthew-blackman and I tested against the true parabolas, and we believe the effect to be an optical illusion.

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/60898831-37df-4d30-ba91-7db42d9349e2)

Closing.
