### ISSUE TITLE
Create "Values" checkbox

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#81]
In the 1/12 design meeting, it was agreed to add a "Values" checkbox to the static tools panel (top right, bottom element of the panel). This checkbox will show the numerical values on the mean and standard deviation displays on the field, and show an info box in the top-left of the histogram with the following text:

Mean = 5.4 m
Standard deviation = 1.2 m
Standard error = 0.5 m

When there is no data, it should say 'No data'.

**Comment by matthew-blackman** [comment]
To clarify, this will only apply to the Variability, Sources and Measures screen.

**Comment by catherinecarter** [comment]
> To clarify, this will only apply to the Variability, Sources and Measures screens.

I only saw the checkbox on the Measures screen, so my comments only apply to the Measures screen.

**Mean/SD Checkboxes**
In reference to this and issue #52 , when I clicked the checkbox for the mean and SD and got a visual cue both on the field and the histogram with no values, it was very nice. It was clear which value was which and I could see the visual connection between the position of each measure, as well as connection between the field and the histogram. Love those!

**Values checkbox** 
- **Values readout**
   - When I then pressed the values button, my eyes were on the field. I didn't initially see the values show up in the histogram only (upper left), and wished I could connect the values to the field and the icons/visual cues of the mean/SD
   - Development-wise, would it be challenging to add values to the field? 
   - I'm unsure whether they would be better to be shown in the histogram also nearer the triangle/arrows since that information is in the upper left box, but we might not need to the info box in the upper left of the histogram if those values appeared in the histogram as well 
      - I'd love to hear how others processed the information in the info box without a more explicit connection to where those values are in the distribution of projectiles

- **Standard Error**
    - I noted the output of the standard error, but searched around for a visual connection to what that was and didn't see one. I remember the discussion in the 1/12 design meeting was to include this numerical output without a visual output, as well as the concern about having a value without a visual connection to the meaning of that number. I agree with the discussion during that time that a number without a visual connection was confusing. Not sure what to do about it, but that's how my brain processed the information (sort of like, I see the mean triangle, the SD arrows, where's the Standard Error visually? I scanned and scanned but didn't find it, leaving me a little confused). 

- **Visibility and size of mean triangle**
   - Color-wise, is difficult for me to find the mean 
      - ![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/6f88ace3-8358-463f-9a92-c2cda73b1520)
   - The triangle is smaller than the one on the Sampling screen. I feel like these should be consistent in size since they're measuring the same summary statistic. Perhaps the one on the Measures screen could be a bit bigger, and the Sampling screen could be a bit smaller to match?

**Comment by matthew-blackman** [comment]
In discussion today, @samreid @catherinecarter and I agreed that there are tradeoffs of putting the 'Values' info box in the histogram.

Pros:
- Saves space in an already busy sim
- Histogram is open by default, so students would see the values info box if they checked 'Values' before closing accordion box
- If a student checks 'Values' with the Mean or SD showing, they can see a change on the field.

Cons:
- It is possible to close the histogram and uncheck Mean and SD, in which case the 'Values' checkbox does not appear to do anything.

We would like to discuss this with the broader design team before moving ahead with this feature.

**Comment by samreid** [comment]
After the changes, it looks like this:

<img width="443" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/679486/aebd8123-dd04-40cc-9b97-6299043bbce9">

@catherinecarter and @matthew-blackman how does this look to you?

**Comment by samreid** [comment]
Today @catherinecarter indicated that the bar over the x is not at its best. It currently looks like this:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/00e2c02a-2ae5-4ef6-89df-e01bd1c38fba)
 
@matthew-blackman and @catherinecarter and I brainstormed options here:
* Using rich text and changing to italics for it
* Using a different unicode character
* Using a different font

Many of these options have tradeoffs in terms of translatability, consistency within the simulation, etc. @matthew-blackman and I observed that `Arial Rounded MT` looks the same except the x bar looks better:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/556f86c0-f7a0-4d9a-b157-79f67f264c70)

Trebuchet MS 12
![image](https://github.com/phetsims/projectile-data-lab/assets/679486/cb950297-86d3-4fe8-b4aa-a29c16c150b6)

Garamond (odd that it says serif but we don't see serifs, so it may be a fallback)
![image](https://github.com/phetsims/projectile-data-lab/assets/679486/fc628d15-8128-4871-8b10-92899725595d)

Brush Script MT
![image](https://github.com/phetsims/projectile-data-lab/assets/679486/bacaf687-8cc4-48ff-9f33-89964153e6cb)

My favorite is the `'Arial Rounded MT'`, but it is not a web safe font, so perhaps Trebuchet or Garamond as a fallback?

**Comment by catherinecarter** [comment]
Garamond looks pretty good, looks pretty close to the Arial we'll see elsewhere in the sim. Trebuchet looks very different from the other words on the screen, which may look 'off' to a user. 

I vote for Garamond.

**Comment by samreid** [comment]
Thanks, I committed Garamond. Anything else for this issue?

**Comment by matthew-blackman** [comment]
Garamond looks good to me as well. Code is in good shape. Closing.

**Comment by arouinfar** [comment]
Reopening. Here's what Garamond looks like on my machine. Looks like the browser was using a fallback font in https://github.com/phetsims/projectile-data-lab/issues/81#issuecomment-1910616492 and not Garamond.

![image](https://github.com/phetsims/projectile-data-lab/assets/8419308/ec5c9e00-df67-4dd5-87f6-e8b31b15f9dc)

**Comment by arouinfar** [comment]
Whoops, looks like I forgot to reopen this when commenting. Reopening for real this time.

**Comment by matthew-blackman** [comment]
Thanks for reopening @arouinfar. @samreid let's try to figure out what font is displayed [here](https://private-user-images.githubusercontent.com/679486/299745408-fc628d15-8128-4871-8b10-92899725595d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTc4NDcsIm5iZiI6MTcwNzc1NzU0NywicGF0aCI6Ii82Nzk0ODYvMjk5NzQ1NDA4LWZjNjI4ZDE1LTgxMjgtNDg3MS04YjEwLTkyODk5NzI1NTk1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNzA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjJmMDUyZmM0N2VhYTRjMzY2YTU5M2JlMDkyNTFkMzk1ZWFhOTlkZjZmMWY3ZWI3NWMzMDlmZmI4ZmM0NTYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tJSZV3GgqmRpMWWleR-oMAKcjtyx2ZsEeyUkJ9rUVNA) and implement it for the values panel.

**Comment by samreid** [comment]
The link in the preceding comment is broken for me, please advise.

**Comment by matthew-blackman** [comment]
Sorry, trying again. It is the screenshot you posted for Garamond in https://github.com/phetsims/projectile-data-lab/issues/81#issuecomment-1910616492

<img width="350" alt="Screen Shot 2024-02-12 at 12 17 48 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/17a75408-145b-4b44-9d37-c4f71912bb69">

**Comment by samreid** [comment]
Excellent! It seems great, thanks. Closing.
