### ISSUE TITLE
Projectile card should not change size

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#84]
In discussing https://github.com/phetsims/projectile-data-lab/issues/69, @samreid @catherinecarter and I agreed that the projectile card should not change size with new data. Let's make the card big enough to support the largest icons/numbers and leave whitespace for the smaller ones.

**Comment by samreid** [comment]
Code changes and runtime behavior look great, thanks. I'll open a side issue for doing the same thing for the Sampling card panel. Closing.
