### ISSUE TITLE
Sampling screen: Histogram thumbnails retained means

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#87]
Not sure how I made this happen, but I was launching from launcher 1, created a bunch of samples (maxed out n=15) while playing with the normal/fast modes for sampling. I switched to launcher 6, and the thumbnails retained the sample means from launcher 1. When I pressed the sample size for n = 5, the histogram thumbnail erased and was empty, but the other thumbnails retained means from launcher 1. Each time I clicked the sample size, the corresponding thumbnail would erase its data.

The image below looks normal, but I have launcher 6 selected but hadn't launched any samples with any of the sample sizes. You can see data in _n_=2 and _n_=40, but none in n=5 or 15 (I had clicked those sample sizes and the data had cleared). You can sort of tell the data isn't from launcher 6 since the means are close together and the bin width is 0.5.

![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/174bafea-04e5-4e91-b254-985e16af24ac)

This is what launcher 6 typically looks like: 
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/b8ebde51-419f-4564-9a05-122d2cc4f0e3)

And when I switched to launcher 5, you can see the same thumbnails as above, but the info in the histogram says launcher 5 (and the histogram has been cleared), but the thumbnail data remains (except for _n_=2 since that's the sample size I was on when I switched launchers). The zoom levels on the thumbnails look different, too.
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/538d7c5e-131e-44a9-b44f-bbedfa079d70)

**Comment by matthew-blackman** [comment]
This is working great and the code looks good. Nice work! I updated one line of documentation in the above commit. @catherinecarter can you review the behavior and close if all is good?

**Comment by catherinecarter** [comment]
I played with it a bunch and didn't find any instances where the thumbnails retained data from a different launcher. Looks good to me! Closing.
