### ISSUE TITLE
MeasuringTapeNode does not support hiding the text

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#89]
From a TODO:

```ts
          // MeasuringTapeNode does not support hiding the text. This is our "hack" to hide it.
          // TODO: Do we want to change common code support for that? Or try a font of 0? See https://github.com/phetsims/projectile-data-lab/issues/25
          textMaxWidth: 1E-6,
```

**Comment by samreid** [comment]
I cannot figure out what that option does or what it is supposed to do. @matthew-blackman can you help?

**Comment by matthew-blackman** [comment]
I tested the option in question and could not see any role that it was playing. It did not impact the text max width, or anything in studio. I removed the unused option in the above commit. Closing.
