### ISSUE TITLE
Should we delete `mysteryLauncherNumberProperty`?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#96]
During #30 @matthew-blackman and I were skeptical about `mysteryLauncherNumberProperty`, can it be deleted and replaced by `launcherProperty`?

**Comment by samreid** [comment]
Would it be OK if ProjectileIO used a ReferenceIO to indicate the mystery launcher number, or should that remain numeric? ProjectileSelectorNode needs a way to look up the correct launcher from the projectile.

**Comment by samreid** [comment]
We made good progress on this today. I'll take next steps on the TODOs then reassign to @matthew-blackman for additional testing.

**Comment by matthew-blackman** [comment]
Everything looks good here and all remaining known issues are being tracked separately. Nice work! Closing.
