### ISSUE TITLE
Focus on the projectile selector is too big

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#98]
While working on #73 I observed the focus on the projectile selector is too big:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/dd0aba92-3a30-4aa4-b99c-9ab17c7e2666)

**Comment by samreid** [comment]
It looks like the focus rectangle is not respecting the clip area of one of the subcomponents. To reproduce the problem, launch one projectile, then tab focus to the projectile selector panel.

Note if you comment out the clip area, then the focus rectangle is correct:

<details>

```diff

Subject: [PATCH] Add instrumentation for the landedProjectileCountProperty, see https://github.com/phetsims/projectile-data-lab/issues/58
---
Index: js/common-vsm/view/ProjectileSelectorNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common-vsm/view/ProjectileSelectorNode.ts b/js/common-vsm/view/ProjectileSelectorNode.ts
--- a/js/common-vsm/view/ProjectileSelectorNode.ts	(revision ec61c6b8d06fa98cf670a6a2b32eae69342acae1)
+++ b/js/common-vsm/view/ProjectileSelectorNode.ts	(date 1706019489281)
@@ -181,12 +181,12 @@
           const height = customLauncherNode.localBounds.height * ( selectedProjectile.launcherConfiguration === 'angle0Raised' ? 0.6 : 0.5 );
 
           // The launcher has a long pedestal that gets clipped off.
-          customLauncherNode.clipArea = Shape.rect(
-            customLauncherNode.localBounds.minX,
-            customLauncherNode.localBounds.minY,
-            customLauncherNode.localBounds.width,
-            height
-          );
+          // customLauncherNode.clipArea = Shape.rect(
+          //   customLauncherNode.localBounds.minX,
+          //   customLauncherNode.localBounds.minY,
+          //   customLauncherNode.localBounds.width,
+          //   height
+          // );
 
           projectileToggleNode.visible = true;
         }

```

</details>

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/2b5ea4de-bf43-42d4-8a88-02d739a6ef5b)

@jessegreenberg can you please advise?

**Comment by jessegreenberg** [comment]
Thanks to @jonathanolson for fixing this one, `visibleBounds` now supports `clipArea`!  I tested in main and it seems fixed in projectile-data-lab - over to @samreid @matthew-blackman to verify or close.

**Comment by samreid** [comment]
We verified it, nice work @jonathanolson and @jessegreenberg. Thanks! Closing.
