### ISSUE TITLE
What's an ideal order of launchers?

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/projectile-data-lab#99]
In design meeting 01/19/24, the order of the launchers came up in terms of what is the ideal order for the launchers. In this post I'm referring to this order: 
<img width="191" alt="image" src="https://github.com/phetsims/projectile-data-lab/assets/109630002/ce52e4e7-cc8c-4b94-b810-82e54d9dfebc">

MB said that in order to hit the learning goals for science the first launcher should have very little variability in the landing positions. For statistics, and especially on the Sampling screen, having a launcher with more variability than the current launcher 1 would be better so students could notice that as the sample size increases, the width of the sampling distribution decreases. The current launcher 1 is difficult to detect this concept (which is the main learning goal of screen 4). 

To solve this dilemma, it was brought up to: 
- verify with HL to see how much variability in launcher 1 could suffice so the main science learning goal is met, or
- use an alternative solution to keep the same order of the launchers on all four screens, but set the default launcher for screen 4 to be different than launcher 1.

My personal opinion is that it seems that making the default launcher something other than launcher 1 for screen 4 only would be strange to a user when the default is launcher 1 for all other screens. I'm not sure this dissonance is good and could make the user confused about why that screen is starting with a different launcher.

I'm hoping we can find a compromise where the default launcher is the number 1 on all screens, but the variability fits the needs of both science and statistics. That said, if we were to change the order of the launchers and after playing with all 6 launchers, any of the launchers except launcher 1 would be an ok switch with launcher 1.

**Comment by matthew-blackman** [comment]
This is being addressed in #56, closing.
